export const ChatSelectors = {
  chat: '[data-qa="chat"]',
  conversationSettingsSelector: '[data-qa="conversation-settings"]',
  entitySelector: '[data-qa="entity-selector"]',
  entitySettings: '[data-qa="entity-settings"]',
  seeFullList: '[data-qa="see-full-list"]',
  recentEntities: '[data-qa="recent"]',
  systemPrompt: '[data-qa="system-prompt"]',
  message: '[data-qa="message"]',
  chatMessages: '[data-qa="chat-messages"]',
  chatMessage: '[data-qa="chat-message"]',
  messageIcon: '[data-qa="message-icon"]',
  messageContent: '[data-qa="message-content"]',
  loadingCursor: '[data-qa="loading-cursor"]',
  temperatureSlider: '[data-qa="temp-slider"]',
  slider: '.temperature-slider',
  addons: '[data-qa="addons"]',
  addon: '[data-qa="addon"]',
  seeAllSelectors: '[data-qa="see-all-addons"]',
  regenerate: '[data-qa="regenerate"]',
  editIcon: '.tabler-icon-edit',
  saveAndSubmit: '[data-qa="save-and-submit"]',
  addonsDialog: '[data-qa="addons-dialog"]',
  addonSearchResults: '[data-qa="addon-search-results"]',
  modelSelector: '[data-qa="model-selector"]',
  listOptions: '[role="listbox"] > [role="option"]',
  combobox: '[role="combobox"]',
};
