export const IconSelectors = {
  editIcon: '.tabler-icon-edit',
  cancelIcon: '.tabler-icon-x',
  deleteIcon: '.tabler-icon-trash-x',
  playbackIcon: '[data-qa="playback-icon"]',
  copyIcon: '.tabler-icon-copy',
  replayIcon: '[data-qa="replay-icon"]',
  promptIcon: '.tabler-icon-bulb',
  listDetailsIcon: '.tabler-icon-list-details',
  helpIcon: '.tabler-icon-help',
  fileIcon: '.tabler-icon-file',
  checkedCircleIcon: '.tabler-icon-circle-check',
  checkIcon: '.tabler-icon-check',
  filledDotCircleIcon: '.tabler-icon-circle-dot-filled',
  dotCircleIcon: '.tabler-icon-circle-dot',
  filledPointIcon: '.tabler-icon-point-filled',
  exclamationCircleIcon: '.tabler-icon-exclamation-circle',
  externalAppIcon: '.tabler-icon-external-link',
  defaultToolsetIcon: '.tabler-icon-blocks.text-primary.dark\\:invert',
  noToolsetIcon: '.tabler-icon.tabler-icon-blocks',
  arrowsMaximizeIcon: '.tabler-icon-arrows-maximize',
  arrowsMinimizeIcon: '.tabler-icon-arrows-minimize',
  plusIcon: '.tabler-icon-plus',
  oauthIcon: '.tabler-icon-brand-oauth',
  keyIcon: '.tabler-icon-key',
  lockOffIcon: '.tabler-icon-lock-off',
};
