export const IconSelectors = {
  editIcon: '.tabler-icon-edit',
  cancelIcon: '.tabler-icon-x',
  deleteIcon: '.tabler-icon-trash-x',
  playbackIcon: '[data-qa="playback-icon"]',
  copyIcon: '.tabler-icon-copy',
  replayIcon: '[data-qa="replay-icon"]',
  promptIcon: '.tabler-icon-bulb',
  listDetailsIcon: '.tabler-icon-list-details',
  helpIcon: '.tabler-icon-help',
  fileIcon: '.tabler-icon-file',
  checkedCircleIcon: '.tabler-icon-circle-check',
  checkIcon: '.tabler-icon-check',
  filledDotCircleIcon: '.tabler-icon-circle-dot-filled',
  dotCircleIcon: '.tabler-icon-circle-dot',
  circleIcon: '.tabler-icon-circle',
  filledPointIcon: '.tabler-icon-point-filled',
  exclamationCircleIcon: '.tabler-icon-exclamation-circle',
  externalAppIcon: '.tabler-icon-external-link',
  defaultToolsetIcon: '.tabler-icon-blocks.text-primary.dark\\:invert',
  noToolsetIcon: '.tabler-icon.tabler-icon-blocks',
  arrowsMaximizeIcon: '.tabler-icon-arrows-maximize',
  arrowsMinimizeIcon: '.tabler-icon-arrows-minimize',
  plusIcon: '.tabler-icon-plus',
  oauthIcon: '.tabler-icon-brand-oauth',
  keyIcon: '.tabler-icon-key',
  lockOffIcon: '.tabler-icon-lock-off',
  dotsMenuIcon: '.tabler-icon-dots-vertical',
  caretIcon: '.tabler-icon-caret-right-filled',
  chevronsRightIcon: '.tabler-icon-chevrons-right',
  chevronRightIcon: '.tabler-icon-chevron-right',
  fileTypeIcon: (extension: string) =>
    `tabler-icon tabler-icon-file-type-${extension} `,
  defaultFileIconClass: 'tabler-icon tabler-icon-file ',
  alertIcon: '.tabler-icon-alert-circle-filled.text-error',
  warningIcon: '.tabler-icon-alert-triangle-filled.text-warning-icon',
  sharedEntityIcon: '.tabler-icon-arrow-up-right',
  eyeIcon: '.tabler-icon.tabler-icon-eye',
  eyeOffIcon: '.tabler-icon.tabler-icon-eye-off',
  chevronDownIcon: '.tabler-icon.tabler-icon-chevron-down',
  chevronUpIcon: '.tabler-icon.tabler-icon-chevron-up',
};
