export const OverlaySelectors = {
  overlayFrame: '[name="overlay"]',
  overlayChatIcon: '[name="open"]',
  overlayManagerCollapseButton: '#collapse-button',
  overlayManagerFullScreenButton: '#full-screen-button',
  overlayManagerContainer: '#frame-container',
};

export const EventSelectors = {
  chatActionsContainer: '#chat-actions',
  sendMessageButton: '[data-qa="send-message"]',
  setSysPromptButton: '[data-qa="set-sys-prompt"]',
  getMessagesButton: '[data-qa="get-messages"]',
  getConversationsButton: '[data-qa="get-conversations"]',
  getSelectedConversationsButton: '[data-qa="get-selected-conversations"]',
  createConversationButton: '[data-qa="create-conversation"]',
  createConversationInFolderButton: '[data-qa="create-conversation-in-folder"]',
  selectConversationByIdButton: '[data-qa="select-conversation-by-id"]',
  conversationIdField: '[data-qa="conversation-id"]',
  newConversationNameField: '[data-qa="conversation-new-name"]',
  configurationContainer: '#configuration',
  setConfigurationButton: '[data-qa="set-configuration"]',
  createLocalConversationButton: '[data-qa="create-local-conversation"]',
  deleteConversationByIdButton: '[data-qa="delete-conversation-by-id"]',
  playbackConversationByIdButton: '[data-qa="playback-conversation-by-id"]',
  renameConversationByIdButton: '[data-qa="rename-conversation-by-id"]',
  exportConversationByIdButton: '[data-qa="export-conversation-by-id"]',
  importedConversationField: '[data-qa="imported-conversation"]',
  importConversationButton: '[data-qa="import-conversation"]',
};
