### IMPORTANT!
### To run the Continuous Integration (CI) process on the main branch,
### you MUST set the variable BUILD_VERSION  (image.tag) when using "no-build" in the CI_COMMIT_MESSAGE.

include:
  - project: "epm-gpt/common/common-ci-templates"
    ref: 0.0.2
    file:
      - "/steps/versioning/semver.yml"
      - "/steps/packaging/docker.yml"
  - project: "epm-gpt/common/common-ci-templates"
    ref: 0.0.0
    file:
      - "/steps/deploy/helm.yml"

stages:
  - test
  - build
  - dry_run
  - deploy

variables:
  HELM_NS_NAME: "epm-gpt-common"
  HELM_CHART: "./helm/chat"
  HELM_RELEASE_NAME: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}"
  HELM_EXTRA_ARGS: " --values ${HELM_EXTRA_VALUES_FILE} --set image.tag=${HELM_APP_IMAGE_TAG} --set secrets.OPENAI_API_KEY=${OPENAI_API_KEY} --set secrets.NEXTAUTH_SECRET=${NEXTAUTH_SECRET} --set secrets.AUTH_TENANT_ID=${AUTH_TENANT_ID} --set secrets.AUTH_CLIENT_SECRET=${AUTH_CLIENT_SECRET} --set secrets.AUTH_CLIENT_ID=${AUTH_CLIENT_ID} --set secrets.REQUEST_API_KEY_CODE=${REQUEST_API_KEY_CODE} --set secrets.REPORT_ISSUE_CODE=${REPORT_ISSUE_CODE}"
  HELM_EXTRA_VALUES_FILE: "./helm/dev.yaml"

prepare_version:
  stage: test
  extends: .semver_prepare_version
  rules:
    - if: "$CI_COMMIT_MESSAGE =~ /no-build/"
      when: never
    - if: "$CI_COMMIT_BRANCH"

build_and_release:
  stage: build
  extends: .build_docker
  rules:
    - if: "$CI_COMMIT_MESSAGE =~ /no-build/"
      when: never
    - if: "$CI_COMMIT_BRANCH"

release:
  stage: build
  extends: .semver_release
  dependencies:
    - "prepare_version"
    - "build_and_release"
  needs:
    - "prepare_version"
    - "build_and_release"
  rules:
    - if: "$CI_COMMIT_MESSAGE =~ /no-build/"
      when: never
    - if: '$CI_COMMIT_REF_NAME  == "main"'

dry_run:
  stage: dry_run
  extends: .helm_diff
  rules:
    - if: '$CI_COMMIT_REF_NAME  == "main"'
      variables:
        HELM_EXTRA_VALUES_FILE: "./helm/main.yaml"
        HELM_APP_IMAGE_TAG: $BUILD_VERSION
    - if: '$CI_COMMIT_REF_NAME  == "dev"'
      variables:
        HELM_EXTRA_VALUES_FILE: "./helm/$CI_COMMIT_REF_NAME.yaml"
        HELM_APP_IMAGE_TAG: $CI_COMMIT_REF_NAME

deploy:
  stage: deploy
  extends: .helm_upgrade
  rules:
    - if: '$CI_COMMIT_REF_NAME  == "main"'
      when: manual
      variables:
        HELM_EXTRA_VALUES_FILE: "./helm/main.yaml"
        HELM_APP_IMAGE_TAG: $BUILD_VERSION
    - if: '$CI_COMMIT_REF_NAME  == "dev"'
      when: on_success
      variables:
        HELM_EXTRA_VALUES_FILE: "./helm/$CI_COMMIT_REF_NAME.yaml"
        HELM_APP_IMAGE_TAG: $CI_COMMIT_REF_NAME
