include:
  - project: "epm-gpt/common/common-ci-templates"
    ref: "main"
    file:
    - "pipelines/cicd/docker_helm.yml"

variables:
  HELM_NS_NAME: "epm-gpt-common"
  HELM_CHART: "./helm/app"
  HELM_EXTRA_ARGS: "--values ./helm/dev.yaml --set secrets.openai_token=${OPENAI_TOKEN_AZURE} --set auth.password='${BASIC_AUTH_HTPASSWD_B64}'"

prepare_version:
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /no-build/

build_and_release:
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /no-build/
