---
excludes:
  paths:
    - pattern: 'package-lock.json'
      reason: 'BUILD_TOOL_OF'
  scopes:
    - pattern: 'devDependencies'
      reason: 'DEV_DEPENDENCY_OF'
      comment: 'Packages for development only.'
license_choices:
  repository_license_choices:
    - given: 'GPL-2.0-only OR MIT'
      choice: 'MIT'
resolutions:
  rule_violations:
    - message: '.*ERROR: NO_LICENSE_IN_DEPENDENCY - NPM::union:0.5.0.*'
      reason: 'CANT_FIX_EXCEPTION'
      comment: 'The dependency has MIT license in github repo'
