---
excludes:
  paths:
    - pattern: 'package-lock.json'
      reason: 'BUILD_TOOL_OF'
  scopes:
    - pattern: 'devDependencies'
      reason: 'DEV_DEPENDENCY_OF'
      comment: 'Packages for development only.'
license_choices:
  repository_license_choices:
    - given: 'GPL-2.0-only OR MIT'
      choice: 'MIT'
    - given: 'GPL-3.0-or-later OR MIT'
      choice: 'MIT'
resolutions:
  rule_violations:
    - message: "No license information is available for dependency \
        'NPM::union:0\\.5\\.0'\\."
      reason: 'CANT_FIX_EXCEPTION'
      comment: 'The dependency has MIT license in github repo'
    - message: "No license information is available for dependency \
        'NPM::stack-trace:0\\.0\\.9'\\."
      reason: 'CANT_FIX_EXCEPTION'
      comment: 'The dependency has MIT license in github repo'
    - message: "No license information is available for dependency \
        'NPM:@mapbox:jsonlint-lines-primitives:2\\.0\\.2'\\."
      reason: 'CANT_FIX_EXCEPTION'
      comment: 'The dependency has MIT license in github repo'
    - message: "No license information is available for dependency \
        'NPM:@plotly:mapbox-gl:1\\.13\\.4'\\."
      reason: 'CANT_FIX_EXCEPTION'
      comment: 'The dependency has BSD-3-Clause license in github repo'
    - message:
        "The license NOASSERTION is currently not covered by policy rules\\. \
        The license was declared in package 'NPM:@plotly:mapbox-gl:1\\.13\\.4'\\."
      reason: 'CANT_FIX_EXCEPTION'
      comment: 'The dependency has BSD-3-Clause license in github repo'
    - message: "No license information is available for dependency \
        'NPM::only:0\\.0\\.2'\\."
      reason: 'CANT_FIX_EXCEPTION'
      comment: 'The dependency has MIT license in github repo'
    - message: "No license information is available for dependency \
        'NPM:@module-federation:bridge-react-webpack-plugin:0\\.2\\.8'\\."
      reason: 'CANT_FIX_EXCEPTION'
      comment: 'The dependency has MIT license in github repo'
    - message: "The dependency 'NPM::node-forge:1\\.3\\.1' is licensed under the ScanCode 'copyleft' categorized license GPL-2\\.0-only\\."
      reason: 'CANT_FIX_EXCEPTION'
      comment: 'The dependency has BSD-3-Clause license in github repo'
    - message: "No license information is available for dependency \
        'NPM::ansi-color:0\\.2\\.1'\\."
      reason: 'CANT_FIX_EXCEPTION'
    - message: "No license information is available for dependency \
        'NPM::process:0\\.10\\.1'\\."
      reason: 'CANT_FIX_EXCEPTION'
      comment: 'The dependency has MIT license in github repo'
