export const errorsMessages = {
  generalClient: 'error.general_client.message',
  generalServer: 'error.general_server.message',
  429: 'error.429.message',
  401: 'error.401.message',
  403: 'error.403.message',
  400: 'error.400.message',
  contentFiltering: 'error.content_filtering.message',
  unsupportedConversationsDataFormat:
    'error.unsupported_conversations_data_format.message',
  unsupportedPromptsDataFormat: 'error.unsupported_prompts_data_format.message',
  localStorageQuotaExceeded: 'error.local_storage_quota_exceeded.message',
  timeoutError: 'error.timeout_error.message',
  customThemesConfigNotProvided:
    'error.custom_themes_config_not_provided.message',
  errorDuringEntityRequest: (entityType: string) =>
    `Error happened during ${entityType} request. Please try again later.`,
  errorGettingUserBucket: 'error.error_getting_user_bucket.message',
  noModelsAvailable: 'error.no_models_available.message',
  importConversationsFailed: 'error.import_conversations_failed.message',
  importPromptsFailed: 'error.import_prompts_failed.message',
  exportFailed: 'error.export_failed.message',
  shareFailed: 'error.share_failed.message',
  acceptShareFailed: 'error.accept_share_failed.message',
  acceptShareNotExists: 'error.accept_share_not_exists.message',
  revokeAccessFailed: 'error.revoke_access_failed.message',
  discardSharedWithMeFailed: 'error.discard_shared_with_me_failed.message',
  shareByMeListingFailed: 'error.share_by_me_listing_failed.message',
  shareWithMeListingFailed: 'error.share_with_me_listing_failed.message',
  notValidEntityType: 'error.not_valid_entity_type.message',

  entityNameInvalid: 'chat.chat_input.name_is_invalid.text',
  entityPathInvalid: 'chat.chat_input.path_is_invalid.text',
  entityNameInvalidExternal: 'chat.chat_input.name_is_invalid.text',
  entityPathInvalidExternal: 'chat.chat_input.path_is_invalid.text',

  publicationFailed: 'error.publication_failed.message',
  publicationsUploadFailed: 'error.publications_upload_failed.message',
  publicationUploadFailed: 'error.publication_upload_failed.message',
  publicationDeletionFailed: 'error.publication_deletion_failed.message',
  publishedItemsUploadFailed: 'error.published_items_upload_failed.message',
  publicationApproveFailed: 'error.publication_approve_failed.message',
  publicationRejectFailed: 'error.publication_reject_failed.message',
  publishingByMeItemsUploadingFailed:
    'error.publishing_by_me_items_uploading_failed.message',
  rulesUploadingFailed: 'error.rules_uploading_failed.message',
};
