apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: {{ include "app.fullname" . }}-auth-secret
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Content-Security-Policy: default-src 'self' data:";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "Cache-control: max-age=60";
      more_set_headers "Strict-Transport-Security: max-age=31536000";

spec:
  rules:
    - host: chatbot-ui.epm-gpt-common.epm-gpt.wedonthavedomainyet.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "app.fullname" . }}
                port:
                  name: http
