apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/server-snippet: |
      return 301 $scheme://chatbot-ui-epm-gpt-common.common.epm-gpt.projects.epam.com$request_uri;
spec:
  rules:
    - host: chatbot-ui.epm-gpt-common.common.epm-gpt.projects.epam.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "app.fullname" . }}
                port:
                  name: http
