apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-auth-secret
type: Opaque
data:
  auth: {{ printf "%s:%s" .Values.auth.user .Values.auth.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}
type: Opaque
data:
  token: {{ .Values.secrets.openai_token | b64enc }}
