import type { ConfigDefinition } from '../app-config.types';

export const CONFIG_DEFINITIONS: ConfigDefinition[] = [
  {
    key: 'asr.modelId',
    type: 'config',
    valueType: 'string',
    visibility: 'client',
    defaultValue: null,
    critical: false,
    description:
      'Deployment ID of the ASR model used for transcription. Null when ASR_MODEL is not configured.',
    owner: 'chat-team',
    envVar: 'ASR_MODEL',
  },
  {
    key: 'asr.transcribeSizeLimitBytes',
    type: 'config',
    valueType: 'number',
    visibility: 'client',
    defaultValue: 5 * 1024 * 1024,
    critical: false,
    description:
      'Maximum audio file size in bytes accepted by the transcription endpoint.',
    owner: 'chat-team',
    envVar: 'TRANSCRIBE_SIZE_LIMIT_BYTES',
  },
  {
    key: 'customVariables',
    type: 'config',
    valueType: 'json',
    visibility: 'client',
    defaultValue: {},
    critical: false,
    description:
      'Public, client-owned configuration values. Keys have no BFF-defined semantics.',
    owner: 'chat-team',
    envVar: 'CUSTOM_CLIENT_VARIABLES',
  },
  {
    key: 'deployments.defaultDeploymentId',
    type: 'config',
    valueType: 'string',
    visibility: 'client',
    defaultValue: null,
    critical: false,
    description:
      'Operator-configured default deployment ID shown to users without a persisted selection. Null when DEFAULT_DEPLOYMENT is not set.',
    owner: 'chat-team',
    envVar: 'DEFAULT_DEPLOYMENT',
  },
  {
    key: 'dialCore.externalUrl',
    type: 'config',
    valueType: 'string',
    visibility: 'client',
    defaultValue: null,
    critical: false,
    description:
      'Public-facing DIAL Core base URL that browsers can reach directly, used to build client-side MCP endpoint links. Null when DIAL_CORE_EXTERNAL_URL is not configured. Distinct from the internal DIAL_CORE_URL, which is never exposed to clients.',
    owner: 'chat-team',
    envVar: 'DIAL_CORE_EXTERNAL_URL',
  },
  {
    key: 'mcpApps.sandboxUrl',
    type: 'config',
    valueType: 'string',
    visibility: 'client',
    defaultValue: null,
    critical: false,
    description:
      'Isolated-origin URL of the deployed MCP Apps sandbox-proxy app (apps/mcp-app-sandbox). Null when MCP_APP_SANDBOX_URL is not configured — the "Open App" trigger and auto-open simply do not appear.',
    owner: 'chat-team',
    envVar: 'MCP_APP_SANDBOX_URL',
  },
  {
    key: 'mcpApps.theme',
    type: 'config',
    valueType: 'string',
    visibility: 'client',
    defaultValue: null,
    critical: false,
    description:
      'Admin-controlled color theme override for all MCP App Views. When set, all users receive this theme in hostContext.theme regardless of their own UI preference. Null when MCP_APP_THEME is not configured — each client falls back to its own active theme.',
    owner: 'chat-team',
    envVar: 'MCP_APP_THEME',
  },
  {
    key: 'mcpApps.userAgent',
    type: 'config',
    valueType: 'string',
    visibility: 'client',
    defaultValue: null,
    critical: false,
    description:
      'Host application identifier sent to MCP App Views in hostContext.userAgent. Defaults to "ai-dial-chat" when MCP_APP_USER_AGENT is not configured.',
    owner: 'chat-team',
    envVar: 'MCP_APP_USER_AGENT',
  },
  {
    key: 'mcpApps.hostName',
    type: 'config',
    valueType: 'string',
    visibility: 'client',
    defaultValue: null,
    critical: false,
    description:
      'Host application identifier sent to every mounted MCP App as hostInfo.name during its ui/initialize handshake. Null when MCP_APP_HOST_NAME is not configured — the client falls back to its own default identity.',
    owner: 'chat-team',
    envVar: 'MCP_APP_HOST_NAME',
  },
  {
    key: 'app.version',
    type: 'config',
    valueType: 'string',
    visibility: 'client',
    defaultValue: null,
    critical: false,
    description:
      'Version string shown in the footer version label and substituted for the %%VERSION%% footer token. Sourced from CHAT_VERSION so CI/CD can stamp the deployed build; falls back to the application package.json version when unset or blank.',
    owner: 'chat-team',
    envVar: 'CHAT_VERSION',
  },
  {
    key: 'announcement.html',
    type: 'config',
    valueType: 'string',
    visibility: 'client',
    defaultValue: null,
    critical: false,
    description:
      'Operator-authored HTML announcement message shown in a dismissible top-of-app banner. Passed through verbatim and sanitized client-side to <a>, <b>, <strong>, <em>, <u>, <br>, <span>, <p>; style attributes are stripped. Null/empty hides the banner. Sourced from ANNOUNCEMENT_HTML_MESSAGE.',
    owner: 'chat-team',
    envVar: 'ANNOUNCEMENT_HTML_MESSAGE',
  },
  {
    key: 'announcement.title',
    type: 'config',
    valueType: 'string',
    visibility: 'client',
    defaultValue: null,
    critical: false,
    description:
      'Operator-authored plain-text heading shown in bold at the start of the announcement banner line. Rendered as text, never as markup. Null/blank omits the heading. Sourced from ANNOUNCEMENT_TITLE.',
    owner: 'chat-team',
    envVar: 'ANNOUNCEMENT_TITLE',
  },
  {
    key: 'announcement.description',
    type: 'config',
    valueType: 'string',
    visibility: 'client',
    defaultValue: null,
    critical: false,
    description:
      'Operator-authored supporting copy shown after the announcement banner title. Sanitized server-side to a safe HTML subset. Null/blank omits the description. Sourced from ANNOUNCEMENT_DESCRIPTION.',
    owner: 'chat-team',
    envVar: 'ANNOUNCEMENT_DESCRIPTION',
  },
  {
    key: 'announcement.items',
    type: 'config',
    valueType: 'json',
    visibility: 'client',
    defaultValue: [],
    critical: false,
    description:
      'List of announcements shown in the popover behind the banner\'s "+N announcements" pill. JSON array of { title, description?, link?: { label, href } }. Entries with a blank title, or with a link whose label is blank or whose href is not http/https, are dropped with a warning. Empty (pill hidden) when ANNOUNCEMENTS is unset or malformed; boot never fails on bad config.',
    owner: 'chat-team',
    envVar: 'ANNOUNCEMENTS',
  },
  {
    key: 'welcomeScreen.description',
    type: 'config',
    valueType: 'string',
    visibility: 'client',
    defaultValue: null,
    critical: false,
    description:
      'Operator-authored plain-text copy shown below the greeting heading on the new-chat start screen. Rendered as text, never as markup. Null/blank hides it. Sourced from WELCOME_SCREEN_DESCRIPTION.',
    owner: 'chat-team',
    envVar: 'WELCOME_SCREEN_DESCRIPTION',
  },
  {
    key: 'footer.html',
    type: 'config',
    valueType: 'string',
    visibility: 'client',
    defaultValue: null,
    critical: false,
    description:
      'Operator-authored HTML footer message shown below the chat input (desktop) and in the mobile user panel. Null/empty hides the footer. Sourced from FOOTER_HTML_MESSAGE. Supports %%VERSION%% token substitution.',
    owner: 'chat-team',
    envVar: 'FOOTER_HTML_MESSAGE',
  },
  {
    key: 'features.footer',
    type: 'feature',
    valueType: 'boolean',
    visibility: 'client',
    defaultValue: false,
    critical: false,
    description:
      'Whether the footer HTML message area is shown. Automatically enabled when FOOTER_HTML_MESSAGE is set.',
    owner: 'chat-team',
  },
  {
    key: 'features.asrEnabled',
    type: 'feature',
    valueType: 'boolean',
    visibility: 'client',
    defaultValue: false,
    critical: false,
    description:
      'Whether ASR (Automatic Speech Recognition) transcription is enabled. Derived from ASR_MODEL presence. Set ASR_ENABLED_ROLES to restrict to specific roles.',
    owner: 'chat-team',
    allowedRolesEnvVar: 'ASR_ENABLED_ROLES',
  },
  {
    key: 'utility.modelId',
    type: 'config',
    valueType: 'string',
    visibility: 'server',
    defaultValue: null,
    critical: false,
    description:
      'Deployment ID of the utility model used for server-side tasks such as LLM conversation naming. Null when UTILITY_MODEL is not configured.',
    owner: 'chat-team',
    envVar: 'UTILITY_MODEL',
  },
  {
    key: 'features.llmConversationNaming',
    type: 'feature',
    valueType: 'boolean',
    visibility: 'server',
    defaultValue: false,
    critical: false,
    description:
      'Whether LLM-based conversation naming runs after the first assistant reply. Derived from UTILITY_MODEL and DIAL_API_KEY presence plus LLM_CONVERSATION_NAMING_ENABLED=true.',
    owner: 'chat-team',
  },
  {
    key: 'features.responsesApiEnabled',
    type: 'feature',
    valueType: 'boolean',
    visibility: 'server',
    defaultValue: false,
    critical: false,
    description:
      'Server-side kill switch for routing eligible generations through the OpenAI Responses API. Even when a deployment reports features.responsesApi=true, Responses is only used when this flag is also true. Defaults to false. Not exposed to the frontend client-config endpoint (visibility: server). Role-based rollout (RESPONSES_API_ENABLED_ROLES) is not implemented — out of scope.',
    owner: 'chat-team',
    envVar: 'RESPONSES_API_ENABLED',
  },
  {
    key: 'features.skillUsageEnabled',
    type: 'feature',
    valueType: 'boolean',
    visibility: 'client',
    defaultValue: false,
    critical: false,
    description:
      'Client-visible kill switch for all skill-usage UI in the chat app: the catalog skill "Use in chat" primary action and the conversation input\'s Skills menu (favorites panel, browse modal, selected-skill chip). Exposed to the frontend client-config endpoint (visibility: client) because it gates UI; every entry point is hidden while false. Defaults to false — the backend contract for sending skills with completions is not designed yet, so the flag ships dark. Role-based rollout (SKILL_USAGE_ENABLED_ROLES) is not implemented — out of scope.',
    owner: 'chat-team',
    envVar: 'SKILL_USAGE_ENABLED',
  },
  {
    key: 'overlay.enabled',
    type: 'config',
    valueType: 'boolean',
    visibility: 'client',
    defaultValue: false,
    critical: false,
    description:
      'Whether the chat-overlay embedded runtime mode is reachable. Distinct from ALLOWED_IFRAME_ORIGINS: has no effect unless at least one origin is also allowlisted there.',
    owner: 'chat-team',
    envVar: 'OVERLAY_ENABLED',
  },
  {
    key: 'overlay.allowedOrigins',
    type: 'config',
    valueType: 'json',
    visibility: 'client',
    defaultValue: [],
    critical: false,
    description:
      'Host origins allowed to embed this app, exposed to the client for self-diagnosis. Sourced from ALLOWED_IFRAME_ORIGINS, the same list that drives CSP frame-ancestors/frame-src.',
    owner: 'chat-team',
    envVar: 'ALLOWED_IFRAME_ORIGINS',
  },
  {
    key: 'fileManager.availableTabs',
    type: 'config',
    valueType: 'json',
    visibility: 'client',
    defaultValue: ['my_files', 'shared', 'organization'],
    critical: false,
    description:
      'Which File Manager tabs are shown to users. Defaults to all three currently-supported tabs when FILE_MANAGER_AVAILABLE_TABS is unset or resolves to no valid ids.',
    owner: 'chat-team',
    envVar: 'FILE_MANAGER_AVAILABLE_TABS',
  },
  {
    key: 'features.liveChatInteraction',
    type: 'feature',
    valueType: 'boolean',
    visibility: 'client',
    defaultValue: false,
    critical: false,
    description:
      'Whether the chat app subscribes to the DIAL Core client channel and shows the ' +
      'interactive toolset sign-in dialog when a completion needs mid-stream toolset ' +
      'credentials. Set LIVE_CHAT_INTERACTION_ENABLED_ROLES to restrict to specific roles.',
    owner: 'chat-team',
    envVar: 'LIVE_CHAT_INTERACTION_ENABLED',
    allowedRolesEnvVar: 'LIVE_CHAT_INTERACTION_ENABLED_ROLES',
  },
  {
    key: 'features.scheduledTasksEnabled',
    type: 'feature',
    valueType: 'boolean',
    visibility: 'client',
    defaultValue: false,
    critical: false,
    description:
      'Whether the Scheduled Tasks feature is enabled, including the DIAL Scheduler ' +
      'proxy endpoints, the Scheduled Tasks page, and its sidebar navigation entry. ' +
      'Set SCHEDULED_TASKS_ENABLED_ROLES to restrict to specific roles.',
    owner: 'chat-team',
    envVar: 'SCHEDULED_TASKS_ENABLED',
    allowedRolesEnvVar: 'SCHEDULED_TASKS_ENABLED_ROLES',
  },
  {
    key: 'features.defaultDeploymentPinned',
    type: 'feature',
    valueType: 'boolean',
    visibility: 'client',
    defaultValue: false,
    critical: false,
    description:
      'When enabled, the operator-configured DEFAULT_DEPLOYMENT is pinned to position 0 ' +
      'in the deployment picker and takes priority over the user-persisted model preference ' +
      'when resolving the initial selection for a new chat.',
    owner: 'chat-team',
    envVar: 'DEFAULT_DEPLOYMENT_PINNED',
  },
  {
    key: 'features.appThemesEnabled',
    type: 'feature',
    valueType: 'boolean',
    visibility: 'client',
    defaultValue: false,
    critical: false,
    description:
      'Whether an application may carry its own theme URL: the Theme URL field in the ' +
      'apps editor, and the host applying that theme while the application is open. ' +
      'Requires THEMES_ALLOWED_ORIGINS to list the origins that may be fetched — with ' +
      'the flag on and no allow-listed origin, every remote theme request is rejected. ' +
      'Deployment-wide; no per-role variable.',
    owner: 'chat-team',
    envVar: 'APP_THEMES_ENABLED',
  },
  {
    key: 'uiFeatures.enabledUiFeatures',
    type: 'config',
    valueType: 'json',
    visibility: 'client',
    defaultValue: null,
    critical: false,
    description:
      'When set, the complete list of OverlayFeature values that are enabled (replace semantics). Replaces DEFAULT_ENABLED_UI_FEATURES entirely — includes both positive and Hide* modifier flags. When not set (null), the compiled-in DEFAULT_ENABLED_UI_FEATURES baseline is used. Does not affect an overlay host that supplies its own enabledFeatures — that replaces the active set entirely.',
    owner: 'chat-team',
    envVar: 'ENABLED_UI_FEATURES',
  },
  {
    key: 'customVisualizers',
    type: 'config',
    valueType: 'json',
    visibility: 'client',
    defaultValue: [],
    critical: false,
    description:
      'Registry of MIME type → visualizer iframe URL mappings. An attachment whose MIME type matches an entry opens in the AttachmentCanvas rendered by that visualizer instead of the default preview. The origin of each entry URL must also be listed in ALLOWED_IFRAME_ORIGINS, which is the sole source of CSP frame-src; otherwise the browser blocks the iframe. Empty (feature dark) when CUSTOM_VISUALIZERS is unset. Invalid JSON or invalid entries are dropped with an error log; boot never fails on malformed config.',
    owner: 'chat-team',
    envVar: 'CUSTOM_VISUALIZERS',
  },
  {
    key: 'applicationVisualizers',
    type: 'config',
    valueType: 'json',
    visibility: 'client',
    defaultValue: {},
    critical: false,
    description:
      'Registry of application id → grouped visualizer mappings, keyed by the effective deployment id of a message. Every attachment the entry claims is delivered to one iframe together via SEND_GROUPED_VISUALIZE_DATA, rendered inline in the message with an expand-to-canvas control. An entry may declare a comma-separated contentType to claim only those MIME types; when it is omitted, every attachment carrying a URL is claimed, and unclaimed attachments render as ordinary tiles. Takes precedence over CUSTOM_VISUALIZERS for the attachments it claims. The origin of each entry URL must also be listed in ALLOWED_IFRAME_ORIGINS, which is the sole source of CSP frame-src; otherwise the browser blocks the iframe. Empty (feature dark) when APPLICATION_VISUALIZERS is unset. Invalid JSON, a non-object value, or invalid entries are dropped with an error log; boot never fails on malformed config.',
    owner: 'chat-team',
    envVar: 'APPLICATION_VISUALIZERS',
  },
  {
    key: 'publish.publicationFilterSources',
    type: 'config',
    valueType: 'json',
    visibility: 'client',
    defaultValue: ['title', 'role', 'dial_roles'],
    critical: false,
    description:
      "Allowed claim/category names selectable as a publication access rule's source. Sourced from PUBLICATION_FILTER_SOURCES (comma-separated); falls back to the legacy default when unset or empty.",
    owner: 'chat-team',
    envVar: 'PUBLICATION_FILTER_SOURCES',
  },
  {
    key: 'attachments.maxFileSizeBytes',
    type: 'config',
    valueType: 'number',
    visibility: 'client',
    defaultValue: 536_870_912,
    critical: false,
    description:
      'Maximum attachment/upload file size in bytes, surfaced to the client so it can reject an oversized file before attempting to upload it. Sourced from FILE_UPLOAD_MAX_BYTES — the same variable that already bounds the POST /api/v1/files Multer limit — so the frontend pre-check and the backend enforcement can never diverge.',
    owner: 'chat-team',
    envVar: 'FILE_UPLOAD_MAX_BYTES',
  },
];
