import type { ConfigDefinition } from '../app-config.types';

export const CONFIG_DEFINITIONS: ConfigDefinition[] = [
  {
    key: 'asr.modelId',
    type: 'config',
    valueType: 'string',
    visibility: 'client',
    defaultValue: null,
    critical: false,
    description:
      'Deployment ID of the ASR model used for transcription. Null when ASR_MODEL is not configured.',
    owner: 'chat-team',
    envVar: 'ASR_MODEL',
  },
  {
    key: 'asr.transcribeSizeLimitBytes',
    type: 'config',
    valueType: 'number',
    visibility: 'client',
    defaultValue: 5 * 1024 * 1024,
    critical: false,
    description:
      'Maximum audio file size in bytes accepted by the transcription endpoint.',
    owner: 'chat-team',
    envVar: 'TRANSCRIBE_SIZE_LIMIT_BYTES',
  },
  {
    key: 'deployments.defaultDeploymentId',
    type: 'config',
    valueType: 'string',
    visibility: 'client',
    defaultValue: null,
    critical: false,
    description:
      'Operator-configured default deployment ID shown to users without a persisted selection. Null when DEFAULT_DEPLOYMENT is not set.',
    owner: 'chat-team',
    envVar: 'DEFAULT_DEPLOYMENT',
  },
  {
    key: 'dialCore.externalUrl',
    type: 'config',
    valueType: 'string',
    visibility: 'client',
    defaultValue: null,
    critical: false,
    description:
      'Public-facing DIAL Core base URL that browsers can reach directly, used to build client-side MCP endpoint links. Null when DIAL_CORE_EXTERNAL_URL is not configured. Distinct from the internal DIAL_CORE_URL, which is never exposed to clients.',
    owner: 'chat-team',
    envVar: 'DIAL_CORE_EXTERNAL_URL',
  },
  {
    key: 'announcement.html',
    type: 'config',
    valueType: 'string',
    visibility: 'client',
    defaultValue: null,
    critical: false,
    description:
      'Operator-authored HTML announcement message shown in a dismissible top-of-app banner. Null/empty hides the banner. Sourced from ANNOUNCEMENT_HTML_MESSAGE.',
    owner: 'chat-team',
    envVar: 'ANNOUNCEMENT_HTML_MESSAGE',
  },
  {
    key: 'footer.html',
    type: 'config',
    valueType: 'string',
    visibility: 'client',
    defaultValue: null,
    critical: false,
    description:
      'Operator-authored HTML footer message shown below the chat input (desktop) and in the mobile user panel. Null/empty hides the footer. Sourced from FOOTER_HTML_MESSAGE. Supports %%VERSION%% token substitution.',
    owner: 'chat-team',
    envVar: 'FOOTER_HTML_MESSAGE',
  },
  {
    key: 'features.footer',
    type: 'feature',
    valueType: 'boolean',
    visibility: 'client',
    defaultValue: false,
    critical: false,
    description:
      'Whether the footer HTML message area is shown. Automatically enabled when FOOTER_HTML_MESSAGE is set.',
    owner: 'chat-team',
  },
  {
    key: 'features.requestApiKey',
    type: 'feature',
    valueType: 'boolean',
    visibility: 'client',
    defaultValue: false,
    critical: false,
    description:
      'Whether the Request API Key dialog is available via the footer data-dial-action trigger. Automatically enabled when REQUEST_API_KEY_CODE is set.',
    owner: 'chat-team',
  },
  {
    key: 'features.reportAnIssue',
    type: 'feature',
    valueType: 'boolean',
    visibility: 'client',
    defaultValue: false,
    critical: false,
    description:
      'Whether the Report an Issue dialog is available via the footer data-dial-action trigger. Automatically enabled when REPORT_ISSUE_CODE is set.',
    owner: 'chat-team',
  },
  {
    key: 'features.asrEnabled',
    type: 'feature',
    valueType: 'boolean',
    visibility: 'client',
    defaultValue: false,
    critical: false,
    description:
      'Whether ASR (Automatic Speech Recognition) transcription is enabled. Derived from ASR_MODEL presence. Set ASR_ENABLED_ROLES to restrict to specific roles.',
    owner: 'chat-team',
    allowedRolesEnvVar: 'ASR_ENABLED_ROLES',
  },
  {
    key: 'utility.modelId',
    type: 'config',
    valueType: 'string',
    visibility: 'server',
    defaultValue: null,
    critical: false,
    description:
      'Deployment ID of the utility model used for server-side tasks such as LLM conversation naming. Null when UTILITY_MODEL is not configured.',
    owner: 'chat-team',
    envVar: 'UTILITY_MODEL',
  },
  {
    key: 'features.llmConversationNaming',
    type: 'feature',
    valueType: 'boolean',
    visibility: 'server',
    defaultValue: false,
    critical: false,
    description:
      'Whether LLM-based conversation naming runs after the first assistant reply. Derived from UTILITY_MODEL and DIAL_API_KEY presence plus LLM_CONVERSATION_NAMING_ENABLED=true.',
    owner: 'chat-team',
  },
  {
    key: 'overlay.enabled',
    type: 'config',
    valueType: 'boolean',
    visibility: 'client',
    defaultValue: false,
    critical: false,
    description:
      'Whether the chat-overlay embedded runtime mode is reachable. Distinct from ALLOWED_IFRAME_ORIGINS: has no effect unless at least one origin is also allowlisted there.',
    owner: 'chat-team',
    envVar: 'OVERLAY_ENABLED',
  },
  {
    key: 'overlay.allowedOrigins',
    type: 'config',
    valueType: 'json',
    visibility: 'client',
    defaultValue: [],
    critical: false,
    description:
      'Host origins allowed to embed this app, exposed to the client for self-diagnosis. Sourced from ALLOWED_IFRAME_ORIGINS, the same list that drives CSP frame-ancestors/frame-src.',
    owner: 'chat-team',
    envVar: 'ALLOWED_IFRAME_ORIGINS',
  },
  {
    key: 'fileManager.availableTabs',
    type: 'config',
    valueType: 'json',
    visibility: 'client',
    defaultValue: ['my_files', 'shared', 'organization'],
    critical: false,
    description:
      'Which File Manager tabs are shown to users. Defaults to all three currently-supported tabs when FILE_MANAGER_AVAILABLE_TABS is unset or resolves to no valid ids.',
    owner: 'chat-team',
    envVar: 'FILE_MANAGER_AVAILABLE_TABS',
  },
  {
    key: 'features.liveChatInteraction',
    type: 'feature',
    valueType: 'boolean',
    visibility: 'client',
    defaultValue: false,
    critical: false,
    description:
      'Whether the chat app subscribes to the DIAL Core client channel and shows the ' +
      'interactive toolset sign-in dialog when a completion needs mid-stream toolset ' +
      'credentials. Set LIVE_CHAT_INTERACTION_ENABLED_ROLES to restrict to specific roles.',
    owner: 'chat-team',
    envVar: 'LIVE_CHAT_INTERACTION_ENABLED',
    allowedRolesEnvVar: 'LIVE_CHAT_INTERACTION_ENABLED_ROLES',
  },
];
