import type { ConfigDefinition } from '../app-config.types';

export const CONFIG_DEFINITIONS: ConfigDefinition[] = [
  {
    key: 'asr.modelId',
    type: 'config',
    valueType: 'string',
    visibility: 'client',
    defaultValue: null,
    critical: false,
    description:
      'Deployment ID of the ASR model used for transcription. Null when ASR_MODEL is not configured.',
    owner: 'chat-team',
    envVar: 'ASR_MODEL',
  },
  {
    key: 'asr.transcribeSizeLimitBytes',
    type: 'config',
    valueType: 'number',
    visibility: 'client',
    defaultValue: 5 * 1024 * 1024,
    critical: false,
    description:
      'Maximum audio file size in bytes accepted by the transcription endpoint.',
    owner: 'chat-team',
    envVar: 'TRANSCRIBE_SIZE_LIMIT_BYTES',
  },
  {
    key: 'deployments.defaultDeploymentId',
    type: 'config',
    valueType: 'string',
    visibility: 'client',
    defaultValue: null,
    critical: false,
    description:
      'Operator-configured default deployment ID shown to users without a persisted selection. Null when DEFAULT_DEPLOYMENT is not set.',
    owner: 'chat-team',
    envVar: 'DEFAULT_DEPLOYMENT',
  },
  {
    key: 'deployments.deepResearchToolId',
    type: 'config',
    valueType: 'string',
    visibility: 'client',
    defaultValue: null,
    critical: false,
    description:
      'Tool ID for the Deep Research deployment-configuration property. When set, the frontend renders a Tools submenu with that tool toggle. Null when DEEP_RESEARCH_TOOL_ID is not set.',
    owner: 'chat-team',
    envVar: 'DEEP_RESEARCH_TOOL_ID',
  },
  {
    key: 'dialCore.externalUrl',
    type: 'config',
    valueType: 'string',
    visibility: 'client',
    defaultValue: null,
    critical: false,
    description:
      'Public-facing DIAL Core base URL that browsers can reach directly, used to build client-side MCP endpoint links. Null when DIAL_CORE_EXTERNAL_URL is not configured. Distinct from the internal DIAL_CORE_URL, which is never exposed to clients.',
    owner: 'chat-team',
    envVar: 'DIAL_CORE_EXTERNAL_URL',
  },
  {
    key: 'app.version',
    type: 'config',
    valueType: 'string',
    visibility: 'client',
    defaultValue: null,
    critical: false,
    description:
      'Version string shown in the footer version label and substituted for the %%VERSION%% footer token. Sourced from CHAT_VERSION so CI/CD can stamp the deployed build; falls back to the application package.json version when unset or blank.',
    owner: 'chat-team',
    envVar: 'CHAT_VERSION',
  },
  {
    key: 'announcement.html',
    type: 'config',
    valueType: 'string',
    visibility: 'client',
    defaultValue: null,
    critical: false,
    description:
      'Operator-authored HTML announcement message shown in a dismissible top-of-app banner. Null/empty hides the banner. Sourced from ANNOUNCEMENT_HTML_MESSAGE.',
    owner: 'chat-team',
    envVar: 'ANNOUNCEMENT_HTML_MESSAGE',
  },
  {
    key: 'announcement.title',
    type: 'config',
    valueType: 'string',
    visibility: 'client',
    defaultValue: null,
    critical: false,
    description:
      'Operator-authored plain-text heading shown in bold at the start of the announcement banner line. Rendered as text, never as markup. Null/blank omits the heading. Sourced from ANNOUNCEMENT_TITLE.',
    owner: 'chat-team',
    envVar: 'ANNOUNCEMENT_TITLE',
  },
  {
    key: 'announcement.description',
    type: 'config',
    valueType: 'string',
    visibility: 'client',
    defaultValue: null,
    critical: false,
    description:
      'Operator-authored supporting copy shown after the announcement banner title. Sanitized server-side to a safe HTML subset. Null/blank omits the description. Sourced from ANNOUNCEMENT_DESCRIPTION.',
    owner: 'chat-team',
    envVar: 'ANNOUNCEMENT_DESCRIPTION',
  },
  {
    key: 'announcement.items',
    type: 'config',
    valueType: 'json',
    visibility: 'client',
    defaultValue: [],
    critical: false,
    description:
      'List of announcements shown in the popover behind the banner\'s "+N announcements" pill. JSON array of { title, description?, link?: { label, href } }. Entries with a blank title, or with a link whose label is blank or whose href is not http/https, are dropped with a warning. Empty (pill hidden) when ANNOUNCEMENTS is unset or malformed; boot never fails on bad config.',
    owner: 'chat-team',
    envVar: 'ANNOUNCEMENTS',
  },
  {
    key: 'footer.html',
    type: 'config',
    valueType: 'string',
    visibility: 'client',
    defaultValue: null,
    critical: false,
    description:
      'Operator-authored HTML footer message shown below the chat input (desktop) and in the mobile user panel. Null/empty hides the footer. Sourced from FOOTER_HTML_MESSAGE. Supports %%VERSION%% token substitution.',
    owner: 'chat-team',
    envVar: 'FOOTER_HTML_MESSAGE',
  },
  {
    key: 'features.footer',
    type: 'feature',
    valueType: 'boolean',
    visibility: 'client',
    defaultValue: false,
    critical: false,
    description:
      'Whether the footer HTML message area is shown. Automatically enabled when FOOTER_HTML_MESSAGE is set.',
    owner: 'chat-team',
  },
  {
    key: 'features.asrEnabled',
    type: 'feature',
    valueType: 'boolean',
    visibility: 'client',
    defaultValue: false,
    critical: false,
    description:
      'Whether ASR (Automatic Speech Recognition) transcription is enabled. Derived from ASR_MODEL presence. Set ASR_ENABLED_ROLES to restrict to specific roles.',
    owner: 'chat-team',
    allowedRolesEnvVar: 'ASR_ENABLED_ROLES',
  },
  {
    key: 'utility.modelId',
    type: 'config',
    valueType: 'string',
    visibility: 'server',
    defaultValue: null,
    critical: false,
    description:
      'Deployment ID of the utility model used for server-side tasks such as LLM conversation naming. Null when UTILITY_MODEL is not configured.',
    owner: 'chat-team',
    envVar: 'UTILITY_MODEL',
  },
  {
    key: 'features.llmConversationNaming',
    type: 'feature',
    valueType: 'boolean',
    visibility: 'server',
    defaultValue: false,
    critical: false,
    description:
      'Whether LLM-based conversation naming runs after the first assistant reply. Derived from UTILITY_MODEL and DIAL_API_KEY presence plus LLM_CONVERSATION_NAMING_ENABLED=true.',
    owner: 'chat-team',
  },
  {
    key: 'overlay.enabled',
    type: 'config',
    valueType: 'boolean',
    visibility: 'client',
    defaultValue: false,
    critical: false,
    description:
      'Whether the chat-overlay embedded runtime mode is reachable. Distinct from ALLOWED_IFRAME_ORIGINS: has no effect unless at least one origin is also allowlisted there.',
    owner: 'chat-team',
    envVar: 'OVERLAY_ENABLED',
  },
  {
    key: 'overlay.allowedOrigins',
    type: 'config',
    valueType: 'json',
    visibility: 'client',
    defaultValue: [],
    critical: false,
    description:
      'Host origins allowed to embed this app, exposed to the client for self-diagnosis. Sourced from ALLOWED_IFRAME_ORIGINS, the same list that drives CSP frame-ancestors/frame-src.',
    owner: 'chat-team',
    envVar: 'ALLOWED_IFRAME_ORIGINS',
  },
  {
    key: 'fileManager.availableTabs',
    type: 'config',
    valueType: 'json',
    visibility: 'client',
    defaultValue: ['my_files', 'shared', 'organization'],
    critical: false,
    description:
      'Which File Manager tabs are shown to users. Defaults to all three currently-supported tabs when FILE_MANAGER_AVAILABLE_TABS is unset or resolves to no valid ids.',
    owner: 'chat-team',
    envVar: 'FILE_MANAGER_AVAILABLE_TABS',
  },
  {
    key: 'features.liveChatInteraction',
    type: 'feature',
    valueType: 'boolean',
    visibility: 'client',
    defaultValue: false,
    critical: false,
    description:
      'Whether the chat app subscribes to the DIAL Core client channel and shows the ' +
      'interactive toolset sign-in dialog when a completion needs mid-stream toolset ' +
      'credentials. Set LIVE_CHAT_INTERACTION_ENABLED_ROLES to restrict to specific roles.',
    owner: 'chat-team',
    envVar: 'LIVE_CHAT_INTERACTION_ENABLED',
    allowedRolesEnvVar: 'LIVE_CHAT_INTERACTION_ENABLED_ROLES',
  },
  {
    key: 'features.scheduledTasksEnabled',
    type: 'feature',
    valueType: 'boolean',
    visibility: 'client',
    defaultValue: false,
    critical: false,
    description:
      'Whether the Scheduled Tasks feature is enabled, including the DIAL Scheduler ' +
      'proxy endpoints, the Scheduled Tasks page, and its sidebar navigation entry. ' +
      'Set SCHEDULED_TASKS_ENABLED_ROLES to restrict to specific roles.',
    owner: 'chat-team',
    envVar: 'SCHEDULED_TASKS_ENABLED',
    allowedRolesEnvVar: 'SCHEDULED_TASKS_ENABLED_ROLES',
  },
  {
    key: 'uiFeatures.enabledUiFeatures',
    type: 'config',
    valueType: 'json',
    visibility: 'client',
    defaultValue: null,
    critical: false,
    description:
      'When set, the complete list of OverlayFeature values that are enabled (replace semantics). Replaces DEFAULT_ENABLED_UI_FEATURES entirely — includes both positive and Hide* modifier flags. When not set (null), the compiled-in DEFAULT_ENABLED_UI_FEATURES baseline is used. Does not affect an overlay host that supplies its own enabledFeatures — that replaces the active set entirely.',
    owner: 'chat-team',
    envVar: 'ENABLED_UI_FEATURES',
  },
  {
    key: 'customVisualizers',
    type: 'config',
    valueType: 'json',
    visibility: 'client',
    defaultValue: [],
    critical: false,
    description:
      'Registry of MIME type → visualizer iframe URL mappings. An attachment whose MIME type matches an entry opens in the AttachmentCanvas rendered by that visualizer instead of the default preview. Empty (feature dark) when CUSTOM_VISUALIZERS is unset. Invalid JSON or invalid entries are dropped with an error log; boot never fails on malformed config.',
    owner: 'chat-team',
    envVar: 'CUSTOM_VISUALIZERS',
  },
  {
    key: 'publish.publicationFilterSources',
    type: 'config',
    valueType: 'json',
    visibility: 'client',
    defaultValue: ['title', 'role', 'dial_roles'],
    critical: false,
    description:
      "Allowed claim/category names selectable as a publication access rule's source. Sourced from PUBLICATION_FILTER_SOURCES (comma-separated); falls back to the legacy default when unset or empty.",
    owner: 'chat-team',
    envVar: 'PUBLICATION_FILTER_SOURCES',
  },
];
