import type { DeploymentCreationFormLocaleEntry } from '@epam/ai-dial-deployment-creation-form';
import type {
  OAuthResourceKind,
  ToolsetAuthTypes,
  ToolsetCredentialsLevel,
  ToolsetOAuthChannelControlType,
  ToolsetOAuthFailureReason,
  ToolsetOAuthInitiationResultType,
  ToolsetOAuthResultType,
  ToolsetTransportType,
  WithLogin,
} from '../constants/toolsets';

export interface ToolsetAuthFormData {
  authenticationType: ToolsetAuthTypes;
  withLogin: WithLogin;
  isLoggedIn: boolean;
  // API_KEY
  keyHeader?: string;
  apiKey?: string;
  // OAUTH
  clientId?: string;
  clientSecret?: string;
  authorizationEndpoint?: string;
  tokenEndpoint?: string;
  scopes?: string[];
  codeChallenge?: string;
  codeChallengeMethod?: string;
}

export interface DeploymentGeneralFormData {
  name: string;
  version: string;
  iconUrl: string;
  description: string;
  topics: string[];
  /** Additional (non-primary) locale entries for name/description, edited via the "Add locale" popup. */
  otherLocales: DeploymentCreationFormLocaleEntry[];
}

export interface ToolsetFormData extends DeploymentGeneralFormData {
  endpoint: string;
  protocol: ToolsetTransportType;
  allowedTools: string[];
  reference?: string;
  auth: ToolsetAuthFormData;
}

export interface ToolsetFormErrors {
  name?: string;
  version?: string;
  endpoint?: string;
  keyHeader?: string;
  apiKey?: string;
  clientId?: string;
  clientSecret?: string;
  authorizationEndpoint?: string;
  tokenEndpoint?: string;
}

/**
 * Redirect state for the admin ToolsetEditor/Catalog OAuth login flow.
 * `initiateOAuthLogin` writes this into the *popup's own* `sessionStorage`
 * before navigating it to the provider, since the popup and its opener do
 * not share a `sessionStorage` partition once navigated cross-origin.
 */
export interface ToolsetRedirectState {
  toolsetId: string;
  credentialsLevel?: ToolsetCredentialsLevel;
  redirectUri?: string;
  /** CSRF state token generated by the client before the OAuth redirect. */
  state?: string;
  /**
   * Which BFF sign-in endpoint the callback route should submit the
   * authorization code to. Defaults to `Toolset` when absent so every
   * existing redirect state (written before this field existed) keeps
   * calling `loginToolset` unchanged. `ExternalService` reuses the same
   * popup/BroadcastChannel machinery with `toolsetId` repurposed as an
   * `{appId}::{serviceId}` composite key.
   */
  resourceKind?: OAuthResourceKind;
}

export type ToolsetOAuthInitiationResult =
  | {
      type: ToolsetOAuthInitiationResultType.Started;
      popup: Window;
      flowId: string;
    }
  | { type: ToolsetOAuthInitiationResultType.Blocked }
  | { type: ToolsetOAuthInitiationResultType.InvalidConfig };

export interface ToolsetOAuthSuccessMessage {
  type: ToolsetOAuthResultType.Success;
  toolsetId: string;
  credentialsLevel: ToolsetCredentialsLevel;
}

export interface ToolsetOAuthFailureMessage {
  type: ToolsetOAuthResultType.Failure;
  reason: ToolsetOAuthFailureReason;
}

/** Confirms that the initiating tab consumed the callback result. */
export interface ToolsetOAuthResultAcknowledgement {
  type: ToolsetOAuthChannelControlType.ResultAcknowledged;
}

/** Non-secret result reported by the OAuth callback popup for one flow. */
export type ToolsetOAuthChannelMessage =
  | ToolsetOAuthSuccessMessage
  | ToolsetOAuthFailureMessage;

/** Result resolved by `waitForToolsetOAuthResult` to the tab that initiated the login. */
export type ToolsetOAuthResult =
  | ToolsetOAuthSuccessMessage
  | ToolsetOAuthFailureMessage
  | { type: ToolsetOAuthResultType.Cancelled };
