import { ApiProperty } from '@nestjs/swagger';
import { IsEnum, IsInt, IsString } from 'class-validator';

/** Lifecycle status of an assistant message generated by a DIAL Core background Responses job. */
export enum BackgroundGenerationStatus {
  Pending = 'pending',
  Completed = 'completed',
  Stopped = 'stopped',
  Failed = 'failed',
}

/**
 * Server-owned association between an assistant message and the DIAL Core background job
 * producing it. `generationId` identifies the message on the background path, because
 * conversation messages have no ids of their own.
 */
export class BackgroundGenerationDto {
  @ApiProperty({
    description:
      'Client-supplied generation id of the request that started the background job; identifies this message across saves.',
    example: '2d0b6c8e-5f7a-4c1b-9e3d-1a2b3c4d5e6f',
  })
  @IsString()
  generationId!: string;

  @ApiProperty({
    enum: BackgroundGenerationStatus,
    enumName: 'BackgroundGenerationStatus',
    description:
      'pending while the job runs or its result is not saved yet; completed, stopped or failed once the final state is saved.',
    example: BackgroundGenerationStatus.Pending,
  })
  @IsEnum(BackgroundGenerationStatus)
  status!: BackgroundGenerationStatus;

  @ApiProperty({
    description:
      'Server time (epoch ms) at which the pending placeholder was saved.',
    example: 1790000000000,
  })
  @IsInt()
  startedAt!: number;
}
