---
name: Feature request
description: Suggest an idea for EPAM AI DIAL chat
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      # yamllint disable rule:line-length
      value: "
        <img src='https://avatars.githubusercontent.com/u/1589802?s=48&v=4' align='left' width='48' height='48'>
        Thank you for finding the time to propose new feature!

        We really appreciate the community efforts to improve EPAM AI DIAL chat.
        <br clear='left'/>"

      # yamllint enable rule:line-length
  - type: textarea
    attributes:
      label: Description
      description: A short description of your feature
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use case/motivation
      description: What would you like to happen?
      placeholder: >
          Rather than telling us how you might implement this feature, try to take a
          step back and describe what you are trying to achieve.
  - type: textarea
    attributes:
      label: Related issues
      description: Is there currently another issue associated with this?
  - type: markdown
    attributes:
      value: "Thanks for completing our form!"
