import type { DisplayAttachment } from '@epam/ai-dial-chat-shared';
import {
  PanelEmpty,
  PanelNoResults,
  SearchInput,
  SidebarOrientation,
  SidebarPanel,
} from '@epam/ai-dial-sidebar';
import { DIAL_ICON_SIZE, DialGhostIconButton } from '@epam/ai-dial-ui-kit';
import { IconDownload } from '@tabler/icons-react';
import { memo, useLayoutEffect, useMemo, useState, type FC } from 'react';
import type { QuotationSource } from '../../models/quotation-source';
import FilesSection from './sections/FilesSection/FilesSection';
import SourcesSection from './sections/SourcesSection/SourcesSection';

/** User-visible strings passed by the consuming app (via i18n or plain strings). */
export interface ConversationSourcesPanelLabels {
  /** Accessible name for the sidebar panel element. */
  ariaLabel: string;
  /** Label for the close button. */
  closeLabel: string;
  /** Placeholder text shown inside the search input. */
  searchPlaceholder: string;
  /** Text shown when the panel has no files or sources. */
  emptyLabel: string;
  /** Text shown when a search query matches nothing. */
  noResultsLabel: string;
  /** Accessible label for the download-all icon button. */
  downloadAllLabel: string;
  /** Heading text for the uploaded-files section. */
  uploadedSectionTitle: string;
  /** Heading text for the generated-files section. */
  generatedSectionTitle: string;
  /** Heading text for the sources section. */
  sourcesSectionTitle: string;
  /** Accessible label for each source's copy-URL button. */
  copySourceLabel: string;
  /** Label passed to each attachment card's action button. */
  attachmentClickLabel: string;
}

/** Optional typography and color class overrides for inner elements. */
export interface ConversationSourcesPanelStyles {
  /** CSS class applied to each section heading (`<h2>`). Defaults to `'dial-body-semi-text'`. */
  sectionTitleClassName?: string;
  /** CSS class applied to each source link. Defaults to `'dial-small-text !text-accent-primary'`. */
  sourceLinkClassName?: string;
  /** CSS class applied to each source quote paragraph. Defaults to `'dial-tiny-text text-secondary'`. */
  sourceQuoteClassName?: string;
}

/** Props for the ConversationSourcesPanel component. */
export interface ConversationSourcesPanelProps {
  /** Whether the panel is currently visible. */
  isOpen: boolean;
  /** Called when the user requests to close the panel. */
  onClose: () => void;
  /** Attachments uploaded by the user in this conversation. */
  uploaded: DisplayAttachment[];
  /** Attachments generated by the assistant in this conversation. */
  generated: DisplayAttachment[];
  /** Quotation sources cited by the assistant. */
  sources: QuotationSource[];
  /** Called when the user activates an attachment card. */
  onAttachmentClick?: (attachment: DisplayAttachment) => void;
  /** Whether the viewport is in mobile breakpoint (disables resizing). */
  isMobile: boolean;
  /** Initial panel width in pixels. */
  defaultWidth?: number;
  /** Minimum panel width in pixels. */
  minWidth?: number;
  /** Maximum panel width in pixels. */
  maxWidth?: number;
  /** Called with the new width after the user finishes a resize drag. */
  onResizeStop?: (width: number) => void;
  /** User-visible strings (titles, placeholders, aria labels). */
  labels: ConversationSourcesPanelLabels;
  /** Optional typography and color class overrides for inner elements. */
  styles?: ConversationSourcesPanelStyles;
}

const includesIgnoreCase = (text: string, query: string): boolean =>
  text.toLowerCase().includes(query.toLowerCase());

const ConversationSourcesPanel: FC<ConversationSourcesPanelProps> = ({
  isOpen,
  onClose,
  uploaded,
  generated,
  sources,
  onAttachmentClick,
  isMobile,
  defaultWidth,
  minWidth,
  maxWidth,
  onResizeStop,
  labels,
  styles,
}) => {
  const [searchQuery, setSearchQuery] = useState('');

  useLayoutEffect(() => {
    if (!isOpen) {
      setSearchQuery('');
    }
  }, [isOpen]);

  const filteredUploaded = useMemo(
    () =>
      searchQuery
        ? uploaded.filter((att) => includesIgnoreCase(att.name, searchQuery))
        : uploaded,
    [uploaded, searchQuery],
  );

  const filteredGenerated = useMemo(
    () =>
      searchQuery
        ? generated.filter((att) => includesIgnoreCase(att.name, searchQuery))
        : generated,
    [generated, searchQuery],
  );

  const filteredSources = useMemo(
    () =>
      searchQuery
        ? sources.filter(
            (s) =>
              includesIgnoreCase(s.title, searchQuery) ||
              includesIgnoreCase(s.url, searchQuery) ||
              (s.quote != null && includesIgnoreCase(s.quote, searchQuery)),
          )
        : sources,
    [sources, searchQuery],
  );

  const isEmpty =
    uploaded.length === 0 && generated.length === 0 && sources.length === 0;
  const isNoResults =
    searchQuery !== '' &&
    filteredUploaded.length === 0 &&
    filteredGenerated.length === 0 &&
    filteredSources.length === 0;

  return (
    <SidebarPanel
      isOpen={isOpen}
      orientation={SidebarOrientation.Right}
      className={isOpen ? 'mobile:w-full' : 'w-0'}
      styles={{
        bodyClassName: 'flex flex-col overflow-hidden p-0',
      }}
      ariaLabel={labels.ariaLabel}
      closeLabel={labels.closeLabel}
      onClose={onClose}
      resizable={!isMobile}
      defaultWidth={defaultWidth}
      minWidth={minWidth}
      maxWidth={maxWidth}
      onResizeStop={onResizeStop}
      rightActions={
        !isEmpty && (
          <DialGhostIconButton
            icon={<IconDownload size={DIAL_ICON_SIZE.LG} stroke={1.5} />}
            aria-label={labels.downloadAllLabel}
            disabled
          />
        )
      }
    >
      {!isEmpty && (
        <SearchInput
          placeholder={labels.searchPlaceholder}
          value={searchQuery}
          onChange={setSearchQuery}
        />
      )}
      <div className="flex-1 overflow-y-auto p-4">
        {isEmpty ? (
          <PanelEmpty label={labels.emptyLabel} />
        ) : isNoResults ? (
          <PanelNoResults label={labels.noResultsLabel} />
        ) : (
          <>
            <FilesSection
              attachments={filteredUploaded}
              title={labels.uploadedSectionTitle}
              titleClassName={styles?.sectionTitleClassName}
              onAttachmentClick={onAttachmentClick}
              attachmentClickLabel={labels.attachmentClickLabel}
            />
            <FilesSection
              attachments={filteredGenerated}
              title={labels.generatedSectionTitle}
              titleClassName={styles?.sectionTitleClassName}
              onAttachmentClick={onAttachmentClick}
              attachmentClickLabel={labels.attachmentClickLabel}
            />
            <SourcesSection
              sources={filteredSources}
              title={labels.sourcesSectionTitle}
              titleClassName={styles?.sectionTitleClassName}
              linkClassName={styles?.sourceLinkClassName}
              quoteClassName={styles?.sourceQuoteClassName}
              copyLabel={labels.copySourceLabel}
            />
          </>
        )}
      </div>
    </SidebarPanel>
  );
};

export default memo(ConversationSourcesPanel);
