export enum ToolsetAuthTypes {
  None = 'NONE',
  ApiKey = 'API_KEY',
  OAuth = 'OAUTH',
}

export enum ToolsetTransportType {
  Http = 'HTTP',
  Sse = 'SSE',
}

export enum ToolsetAuthStatus {
  SignedIn = 'SIGNED_IN',
  SignedOut = 'SIGNED_OUT',
  Failed = 'FAILED',
}

export enum ToolsetCredentialsLevel {
  Global = 'GLOBAL',
  User = 'USER',
  App = 'APP',
}

export enum ToolsetEditorSteps {
  General = 'general',
  Settings = 'settings',
}

export enum WithLogin {
  WithLogin = 'with-login',
  WithoutLogin = 'without-login',
  WithConfig = 'with-config',
}

export interface ToolsetAuthFormData {
  authenticationType: ToolsetAuthTypes;
  withLogin: WithLogin;
  isLoggedIn: boolean;
  // API_KEY
  keyHeader?: string;
  apiKey?: string;
  // OAUTH
  clientId?: string;
  clientSecret?: string;
  authorizationEndpoint?: string;
  tokenEndpoint?: string;
  scopes?: string[];
  codeChallenge?: string;
  codeChallengeMethod?: string;
}

export interface ToolsetFormData {
  name: string;
  version: string;
  iconUrl: string;
  description: string;
  topics: string[];
  intro: string;
  endpoint: string;
  protocol: ToolsetTransportType;
  allowedTools: string[];
  reference?: string;
  auth: ToolsetAuthFormData;
}

export interface ToolsetFormErrors {
  name?: string;
  version?: string;
  intro?: string;
  endpoint?: string;
  keyHeader?: string;
  apiKey?: string;
  clientId?: string;
  clientSecret?: string;
  authorizationEndpoint?: string;
  tokenEndpoint?: string;
}

/**
 * Redirect state for the admin ToolsetEditor/Catalog OAuth login flow.
 * `initiateOAuthLogin` writes this into the *popup's own* `sessionStorage`
 * before navigating it to the provider, since the popup and its opener do
 * not share a `sessionStorage` partition once navigated cross-origin.
 */
export interface ToolsetRedirectState {
  toolsetId: string;
  credentialsLevel?: ToolsetCredentialsLevel;
  redirectUri?: string;
  /** CSRF state token generated by the client before the OAuth redirect. */
  state?: string;
}

/** Outcome of calling `initiateOAuthLogin`. */
export enum ToolsetOAuthInitiationResultType {
  /** The popup was opened and navigated to the provider's authorize URL. */
  Started = 'started',
  /** The browser blocked the popup before it could be opened. */
  Blocked = 'blocked',
  /** The toolset's OAuth configuration is missing required fields. */
  InvalidConfig = 'invalid-config',
}

export type ToolsetOAuthInitiationResult =
  | {
      type: ToolsetOAuthInitiationResultType.Started;
      popup: Window;
      flowId: string;
    }
  | { type: ToolsetOAuthInitiationResultType.Blocked }
  | { type: ToolsetOAuthInitiationResultType.InvalidConfig };

/** Outcome reported back to the tab that initiated an OAuth login. */
export enum ToolsetOAuthResultType {
  Success = 'success',
  Failure = 'failure',
  /** The popup was closed and focus returned to its opener, or the flow timed out. */
  Cancelled = 'cancelled',
}

/** Reason codes the callback popup can report for a failed OAuth login. */
export enum ToolsetOAuthFailureReason {
  MissingCode = 'missing-code',
  MissingRedirectState = 'missing-redirect-state',
  StateMismatch = 'state-mismatch',
  LoginRequestFailed = 'login-request-failed',
}

export interface ToolsetOAuthSuccessMessage {
  type: ToolsetOAuthResultType.Success;
  toolsetId: string;
  credentialsLevel: ToolsetCredentialsLevel;
}

export interface ToolsetOAuthFailureMessage {
  type: ToolsetOAuthResultType.Failure;
  reason: ToolsetOAuthFailureReason;
}

/** Control messages exchanged over a flow-scoped OAuth channel. */
export enum ToolsetOAuthChannelControlType {
  ResultAcknowledged = 'result-acknowledged',
}

/** Confirms that the initiating tab consumed the callback result. */
export interface ToolsetOAuthResultAcknowledgement {
  type: ToolsetOAuthChannelControlType.ResultAcknowledged;
}

/** Non-secret result reported by the OAuth callback popup for one flow. */
export type ToolsetOAuthChannelMessage =
  | ToolsetOAuthSuccessMessage
  | ToolsetOAuthFailureMessage;

/** Result resolved by `waitForToolsetOAuthResult` to the tab that initiated the login. */
export type ToolsetOAuthResult =
  | ToolsetOAuthSuccessMessage
  | ToolsetOAuthFailureMessage
  | { type: ToolsetOAuthResultType.Cancelled };
