export enum ToolsetAuthTypes {
  None = 'NONE',
  ApiKey = 'API_KEY',
  OAuth = 'OAUTH',
}

export enum ToolsetTransportType {
  Http = 'HTTP',
  Sse = 'SSE',
}

export enum ToolsetAuthStatus {
  SignedIn = 'SIGNED_IN',
  SignedOut = 'SIGNED_OUT',
  Failed = 'FAILED',
}

export enum ToolsetCredentialsLevel {
  Global = 'GLOBAL',
  User = 'USER',
  App = 'APP',
}

export enum ToolsetEditorSteps {
  General = 'general',
  Settings = 'settings',
}

export enum WithLogin {
  WithLogin = 'with-login',
  WithoutLogin = 'without-login',
  WithConfig = 'with-config',
}

export interface ToolsetAuthFormData {
  authenticationType: ToolsetAuthTypes;
  withLogin: WithLogin;
  isLoggedIn: boolean;
  // API_KEY
  keyHeader?: string;
  apiKey?: string;
  // OAUTH
  clientId?: string;
  clientSecret?: string;
  authorizationEndpoint?: string;
  tokenEndpoint?: string;
  scopes?: string[];
}

export interface ToolsetFormData {
  name: string;
  version: string;
  iconUrl: string;
  description: string;
  topics: string[];
  intro: string;
  endpoint: string;
  protocol: ToolsetTransportType;
  allowedTools: string[];
  reference?: string;
  auth: ToolsetAuthFormData;
}

export interface ToolsetFormErrors {
  name?: string;
  version?: string;
  intro?: string;
  endpoint?: string;
  keyHeader?: string;
  apiKey?: string;
  clientId?: string;
  clientSecret?: string;
}

export interface ToolsetRedirectState {
  toolsetId: string;
  credentialsLevel?: ToolsetCredentialsLevel;
  callbackUrl?: string;
  /** CSRF state token generated by the client before the OAuth redirect. */
  state?: string;
}
