export enum ToolsetAuthTypes {
  None = 'NONE',
  ApiKey = 'API_KEY',
  OAuth = 'OAUTH',
}

export enum ToolsetTransportType {
  Http = 'HTTP',
  Sse = 'SSE',
}

export enum ToolsetAuthStatus {
  SignedIn = 'SIGNED_IN',
  SignedOut = 'SIGNED_OUT',
  Failed = 'FAILED',
}

export enum ToolsetCredentialsLevel {
  Global = 'GLOBAL',
  User = 'USER',
  App = 'APP',
}

export enum ToolsetEditorSteps {
  General = 'general',
  Settings = 'settings',
}

export enum WithLogin {
  WithLogin = 'with-login',
  WithoutLogin = 'without-login',
  WithConfig = 'with-config',
}

export interface ToolsetAuthFormData {
  authenticationType: ToolsetAuthTypes;
  withLogin: WithLogin;
  isLoggedIn: boolean;
  // API_KEY
  keyHeader?: string;
  apiKey?: string;
  // OAUTH
  clientId?: string;
  clientSecret?: string;
  authorizationEndpoint?: string;
  tokenEndpoint?: string;
  scopes?: string[];
  codeChallenge?: string;
  codeChallengeMethod?: string;
}

export interface ToolsetFormData {
  name: string;
  version: string;
  iconUrl: string;
  description: string;
  topics: string[];
  intro: string;
  endpoint: string;
  protocol: ToolsetTransportType;
  allowedTools: string[];
  reference?: string;
  auth: ToolsetAuthFormData;
}

export interface ToolsetFormErrors {
  name?: string;
  version?: string;
  intro?: string;
  endpoint?: string;
  keyHeader?: string;
  apiKey?: string;
  clientId?: string;
  clientSecret?: string;
}

/**
 * Payload carried in the OAuth `state` query parameter for the admin
 * ToolsetEditor/Catalog login flow. `initiateOAuthLogin` opens the provider
 * in a new window with `noopener`, which severs `sessionStorage` sharing
 * with that window, so this state must round-trip through the IdP inside
 * `state` itself rather than being persisted to `sessionStorage`.
 */
export interface ToolsetRedirectState {
  toolsetId: string;
  credentialsLevel: ToolsetCredentialsLevel;
  /** Opaque token generated by the client before the OAuth redirect. */
  csrfToken: string;
}

/**
 * Payload carried in the OAuth `state` query parameter for a popup-based
 * login initiated from an embedded iframe (e.g. `ai-dial-quickapps-frontend`).
 * Encoded by the caller; this app only decodes and validates it.
 */
export interface ToolsetPopupState {
  toolsetId: string;
  credentialsLevel: ToolsetCredentialsLevel;
  originatingOrigin: string;
  nonce: string;
}
