{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
    {{- if .Values.labels }}
    {{- include "app.tplvalues.render" ( dict "value" .Values.labels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.annotations }}
  annotations: {{- include "app.tplvalues.render" ( dict "value" .Values.annotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ tpl $value $ | b64enc | quote }}
  {{- end }}
{{- end }}