export enum Feature {
  ConversationsSection = 'conversations-section',
  PromptsSection = 'prompts-section',
  TopSection = 'top-settings',
  TopClearСonversation = 'top-clear-conversation',
  TopChatInfo = 'top-chat-info',
  TopChatModelSettings = 'top-chat-model-settings',
  EmptyChatSettings = 'empty-chat-settings',
  Header = 'header',
  Footer = 'footer',
  RequestApiKey = 'request-api-key',
  ReportAnIssue = 'report-an-issue',
  Likes = 'likes',
  ConversationsSharing = 'conversations-sharing',
  PromptsSharing = 'prompts-sharing',
}

export const availableFeatures: Record<Feature, boolean> = {
  'conversations-section': true,
  'prompts-section': true,
  'top-settings': true,
  'top-clear-conversation': true,
  'top-chat-info': true,
  'top-chat-model-settings': true,
  'empty-chat-settings': true,
  header: true,
  footer: true,
  'request-api-key': true,
  'report-an-issue': true,
  likes: true,
  'conversations-sharing': true,
  'prompts-sharing': true,
};
