export enum Attributes {
  value = 'value',
  class = 'class',
  hidden = 'hidden',
  placeholder = 'placeholder',
  type = 'type',
  name = 'name',
  alt = 'alt',
  src = 'src',
  disabled = 'disabled',
  style = 'style',
  ariaLabel = 'aria-label',
  visible = 'visible',
  invisible = 'invisible',
  rotated90 = 'rotate-90',
  rotated180 = 'rotate-180',
  download = 'download',
  href = 'href',
  target = 'target',
  dataQA = 'data-qa',
  ariaSelected = 'aria-selected',
  ariaChecked = 'aria-checked',
  id = 'id',
  ariaExpanded = 'aria-expanded',
  ariaDetails = 'aria-details',
  ariaColcount = 'aria-colcount',
  checked = 'checked',
}

export enum AttributeValues {
  login = 'Log in',
  logout = 'Log out',
  cancelAllRules = 'cancel-all-rules',
  sendRequest = 'Send request',
  change = 'Change',
  copyLink = 'copy-link',
  close = 'Close dialog',
  checkbox = 'checkbox',
  removeFile = 'remove-file',
  mixed = 'mixed',
  truncate = 'truncate',
  lineClamp = 'line-clamp-',
  blank = '_blank',
  textLeft = 'text-left',
  aspectAuto = 'aspect-auto',
  maxHFull = 'max-h-full',
  maxWFull = 'max-w-full',
  password = 'password',
  text = 'text',
  textEllipsis = 'text-ellipsis',
}
