export enum Attributes {
  value = 'value',
  class = 'class',
  hidden = 'hidden',
  placeholder = 'placeholder',
  name = 'name',
  alt = 'alt',
  src = 'src',
  disabled = 'disabled',
  style = 'style',
  ariaLabel = 'aria-label',
  visible = 'visible',
  invisible = 'invisible',
  rotated = 'rotate-90',
  download = 'download',
  href = 'href',
}
