export enum Tags {
  span = 'span',
  textarea = 'textarea',
  button = 'button',
  input = 'input',
  div = 'div',
  svg = 'svg',
  img = 'img',
  a = 'a',
  table = 'table',
  thead = 'thead',
  th = 'th',
  tbody = 'tbody',
  td = 'td',
  html = 'html',
  label = 'label',
}
