import type {
  OAuthResourceKind,
  ToolsetCredentialsLevel,
  ToolsetOAuthChannelControlType,
  ToolsetOAuthFailureReason,
  ToolsetOAuthInitiationResultType,
  ToolsetOAuthResultType,
} from './types';

/**
 * OAuth client settings needed to build an authorize URL — the narrow subset
 * of a toolset's `authSettings` this module reads. Declared as its own shape
 * so hosts can keep their wider editor form models app-owned and still pass
 * them straight in.
 */
export interface ToolsetOAuthSettings {
  clientId?: string;
  authorizationEndpoint?: string;
  scopes?: string[];
  codeChallenge?: string;
  codeChallengeMethod?: string;
}

/**
 * Redirect state for an OAuth login flow. The flow writes this into the
 * *popup's own* `sessionStorage` before navigating it to the provider, since
 * the popup and its opener do not share a `sessionStorage` partition once
 * navigated cross-origin.
 */
export interface ToolsetRedirectState {
  toolsetId: string;
  credentialsLevel?: ToolsetCredentialsLevel;
  redirectUri?: string;
  /** CSRF state token generated by the client before the OAuth redirect. */
  state?: string;
  /**
   * Which sign-in endpoint the host's callback route should submit the
   * authorization code to. Defaults to `Toolset` when absent so every
   * existing redirect state (written before this field existed) keeps
   * calling the toolset login unchanged. `ExternalService` reuses the same
   * popup/BroadcastChannel machinery with `toolsetId` repurposed as an
   * `{appId}::{serviceId}` composite key. `OfflineCredentials` reuses the
   * same machinery again, with `toolsetId` repurposed as a fixed sentinel
   * correlation id (`'offline-credentials'`) — the field carries no real
   * toolset/external-service meaning there, only the opaque
   * flow-correlation string the shared popup/`BroadcastChannel` utilities
   * require structurally.
   */
  resourceKind?: OAuthResourceKind;
  /**
   * Whether the user agreed the application may use the resulting credential
   * while they are away. Carried through the popup because the choice is made
   * before the redirect and the code exchange happens after it — the callback
   * route has no other way to learn it. Absent means "not granted".
   */
  offlineUsageConsent?: boolean;
  /**
   * Main-window mode marker, written by `navigateToolsetOAuthRedirect`: the
   * flow redirected this same window (not a popup) to the provider, so the
   * callback should hand completion to the host's `onMainWindowComplete`
   * (which sends the user back to this path) instead of reporting over the
   * flow channel and closing a popup. Absent in every popup flow.
   */
  returnPath?: string;
}

/**
 * Completion outcome handed to the host's `onMainWindowComplete` callback —
 * see `useOAuthCallbackCompletion`.
 */
export type ToolsetOAuthMainWindowOutcome =
  | { type: ToolsetOAuthResultType.Success }
  | {
      type: ToolsetOAuthResultType.Failure;
      reason: ToolsetOAuthFailureReason;
    };

export type ToolsetOAuthInitiationResult =
  | {
      type: ToolsetOAuthInitiationResultType.Started;
      popup: Window;
      flowId: string;
    }
  | { type: ToolsetOAuthInitiationResultType.Blocked }
  | { type: ToolsetOAuthInitiationResultType.InvalidConfig };

export interface ToolsetOAuthSuccessMessage {
  type: ToolsetOAuthResultType.Success;
  toolsetId: string;
  credentialsLevel: ToolsetCredentialsLevel;
}

export interface ToolsetOAuthFailureMessage {
  type: ToolsetOAuthResultType.Failure;
  reason: ToolsetOAuthFailureReason;
}

/** Confirms that the initiating tab consumed the callback result. */
export interface ToolsetOAuthResultAcknowledgement {
  type: ToolsetOAuthChannelControlType.ResultAcknowledged;
}

/**
 * Non-secret result reported by the OAuth callback popup for one flow. Used
 * unchanged by every resource kind — the callback branch only needs to signal
 * success/failure, not resource details, back through the channel.
 */
export type ToolsetOAuthChannelMessage =
  ToolsetOAuthSuccessMessage | ToolsetOAuthFailureMessage;

/** Result resolved by `waitForToolsetOAuthResult` to the tab that initiated the login. */
export type ToolsetOAuthResult =
  | ToolsetOAuthSuccessMessage
  | ToolsetOAuthFailureMessage
  | { type: ToolsetOAuthResultType.Cancelled };
