/** File extensions that are rendered as HTML in a sandboxed iframe. */
export const HTML_EXTENSIONS = new Set(['html', 'htm']);

/** MIME types for the supported Office Open XML formats. */
export const OOXML_MIME_TYPES = {
  docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  pptx: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
} as const;

/** File extensions that are known to be previewable as plain text. */
export const TEXT_EXTENSIONS = new Set([
  'txt',
  'md',
  'markdown',
  'json',
  'jsonl',
  'ndjson',
  'xml',
  'csv',
  'tsv',
  'yaml',
  'yml',
  'toml',
  'ini',
  'conf',
  'cfg',
  'css',
  'scss',
  'sass',
  'less',
  'js',
  'jsx',
  'ts',
  'tsx',
  'mjs',
  'cjs',
  'mts',
  'cts',
  'py',
  'rb',
  'go',
  'rs',
  'java',
  'kt',
  'swift',
  'c',
  'h',
  'cpp',
  'cs',
  'sh',
  'bash',
  'zsh',
  'fish',
  'ps1',
  'log',
  'env',
  'gitignore',
  'dockerfile',
  'makefile',
  'sql',
]);
