image:
  pullPolicy: Always

replicaCount: 2

env:
  NEXTAUTH_URL: "https://chat.lab.epam.com"
  # OPENAI_API_HOST: "https://southcentralus.api.cognitive.microsoft.com/"
  OPENAI_API_HOST: "http://openai-proxy-main.epm-gpt-common.svc.cluster.local"
  DEFAULT_MODEL: "gpt-35-turbo"
  OPENAI_API_TYPE: "azure"
  OPENAI_API_VERSION: "2023-03-15-preview"
  NEXT_PUBLIC_SHOW_MODELS: "true"
  # simple hack to re-deploy each time. used on DEV to pull "latest" each time with image.pullPolicy:Always
  RELEASE_DATE: '{{ dateInZone "2006-01-02 15:04:05Z" (now) "UTC" }}'
  NEXT_PUBLIC_DEFAULT_SYSTEM_PROMPT: ""
  NEXT_PUBLIC_MAX_TOKENS: "4000"

podLabels:
  azure.workload.identity/use: "true"

# affinity:
#   podAntiAffinity:
#     preferredDuringSchedulingIgnoredDuringExecution:
#       - weight: 100
#         podAffinityTerm:
#           labelSelector:
#             matchExpressions:
#               - key: app
#                 operator: In
#                 values:
#                   - {{ include "app.fullname" . }}
#           topologyKey: kubernetes.io/hostname

ingress:
  enabled: true
  ingressClassName: nginx
  # annotations:
  #   nginx.ingress.kubernetes.io/configuration-snippet: |
  #     more_set_headers "Content-Security-Policy: default-src 'self' data:";
  #     more_set_headers "X-Content-Type-Options: nosniff";
  #     more_set_headers "Cache-control: max-age=60";
  #     more_set_headers "Strict-Transport-Security: max-age=31536000";
  hosts:
    - chat.lab.epam.com
  tls:
    - secretName: wildcard-lab-epam-com
      hosts:
        - chat.lab.epam.com

serviceAccount:
  create: false
  name: epm-gpt-common

# extraEnvVarsSecret: "chat-lab-test"
