image:
  pullPolicy: Always
  tag: dev

replicaCount: 1

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
     cpu: 0.25
     memory: 512Mi

env:
  NEXTAUTH_URL: "https://dev-chat.ai-proxy.lab.epam.com"
  # OPENAI_API_HOST: "https://southcentralus.api.cognitive.microsoft.com/"
  OPENAI_API_HOST: "http://openai-proxy-dev.epm-gpt-common.svc.cluster.local"
  DEFAULT_MODEL: "gpt-35-turbo"
  OPENAI_API_TYPE: "azure"
  OPENAI_API_VERSION: "2023-03-15-preview"
  NEXT_PUBLIC_SHOW_MODELS: "true"
  NEXT_PUBLIC_DEFAULT_SYSTEM_PROMPT: ""
  NEXT_PUBLIC_MAX_TOKENS: "4000"

podLabels:
  azure.workload.identity/use: "true"

podAnnotations:
  autorestart: '{{ dateInZone "2006-01-02 15:04:05Z" (now) "UTC" }}'

# affinity:
#   podAntiAffinity:
#     preferredDuringSchedulingIgnoredDuringExecution:
#       - weight: 100
#         podAffinityTerm:
#           labelSelector:
#             matchExpressions:
#               - key: app
#                 operator: In
#                 values:
#                   - {{ include "app.fullname" . }}
#           topologyKey: kubernetes.io/hostname

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - dev-chat.ai-proxy.lab.epam.com
  tls:
    - secretName: cert-zerossl-aiproxy
      hosts:
        - dev-chat.ai-proxy.lab.epam.com

serviceAccount:
  create: false

# extraEnvVarsSecret: "chat-lab-test"
