image:
  pullPolicy: Always
  registry: registry-dev.deltixhub.com
  tag: development
  pullSecrets:
    - epm-rtc-registry-dev

replicaCount: 1

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 0.25
    memory: 512Mi

env:
  NEXTAUTH_URL: 'https://chat.staging.deltixhub.io'
  # OPENAI_API_HOST: "https://southcentralus.api.cognitive.microsoft.com/"
  OPENAI_API_HOST: 'http://dial-proxy.dial-proxy'
  DEFAULT_MODEL: 'gpt-35-turbo'
  OPENAI_API_VERSION: '2023-03-15-preview'
  NEXT_PUBLIC_DEFAULT_SYSTEM_PROMPT: ''
  AUTH_AUTH0_HOST: 'https://chatbot-ui-staging.eu.auth0.com'
  AUTH_AUTH0_AUDIENCE: 'chat'
  FOOTER_HTML_MESSAGE: '<a href="https://kb.epam.com/display/EPMGPT/EPAM+AI+Chat" target="_blank" rel="noreferrer"> <u><strong>EPAM AI Chat</strong></u> </a>&nbsp;can be used <u>any work-related activity</u>. Rest assured, information you share here is&nbsp;<u> not disclosed to third-party companies </u>. However, we <u>anonymize and log</u> all interactions for research purposes. <br/>For API access please fill&nbsp;<a href="#requestApiKey"><u><strong>this form</strong></u></a>.&nbsp;If you have a problem please&nbsp;<a href="#reportAnIssue"><u><strong>report an issue</strong></u></a>. Version %%VERSION%%'
  NEXT_PUBLIC_APP_NAME: 'DIAL - Staging'
  ENABLED_FEATURES: 'conversations-section,prompts-section,top-settings,top-clear-conversation,top-chat-info,top-chat-model-settings,empty-chat-settings,header,footer,request-api-key,report-an-issue,likes'
  AUTH_DISABLED: 'false'
  IS_IFRAME: 'false'
  AVAILABLE_MODELS_USERS_LIMITATIONS: ''
  AVAILABLE_ADDONS_USERS_LIMITATIONS: ''
  THEMES_CONFIG_HOST: 'https://epam-dial-themes.staging.deltixhub.io'
  RECENT_MODELS_IDS: 'gpt-35-turbo,gpt-4,epam10k-semantic-search,gpt-world,mirror'
  RECENT_ADDONS_IDS: 'addon-epam10k-golden-qna,addon-epam10k-semantic-search,addon-wolfram'

#  AZURE_FUNCTIONS_API_HOST: "https://ai-proxy-function.azurewebsites.net"

# podLabels:
#   azure.workload.identity/use: "true"

# extraEnvVarsSecret: "chat-manual"

podAnnotations:
  autorestart: '{{ dateInZone "2006-01-02 15:04:05Z" (now) "UTC" }}'

# affinity:
#   podAntiAffinity:
#     preferredDuringSchedulingIgnoredDuringExecution:
#       - weight: 100
#         podAffinityTerm:
#           labelSelector:
#             matchExpressions:
#               - key: app
#                 operator: In
#                 values:
#                   - {{ include "app.fullname" . }}
#           topologyKey: kubernetes.io/hostname

ingress:
  enabled: true
  ingressClassName: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: 'internet-facing'
    alb.ingress.kubernetes.io/target-type: 'ip'
    alb.ingress.kubernetes.io/backend-protocol: 'HTTP'
    alb.ingress.kubernetes.io/healthcheck-path: '/'
    alb.ingress.kubernetes.io/healthcheck-protocol: 'HTTP'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/target-group-attributes: 'stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=86400'
    alb.ingress.kubernetes.io/load-balancer-attributes: 'routing.http2.enabled=true'
    alb.ingress.kubernetes.io/listen-ports: '[{ "HTTP" : 80, "HTTPS" : 443 }]'
    alb.ingress.kubernetes.io/ssl-policy: 'ELBSecurityPolicy-TLS-1-2-Ext-2018-06'
    alb.ingress.kubernetes.io/certificate-arn: 'arn:aws:acm:eu-north-1:725751206603:certificate/373e8fd1-088e-4022-adf1-5f3e7820fb4a'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/group.name: 'allow-all'
  hosts:
    - chat.staging.deltixhub.io

serviceAccount:
  create: true
  name: chat
# extraEnvVarsSecret: "chat-lab-test"

service:
  extraPorts:
    - name: metrics
      port: 9464
      targetPort: 9464

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
    port: metrics
    # path: "/metrics"   # default
    interval: '10s'
    labels:
      monitoring: application
