replicaCount: 2

env:
  NEXTAUTH_URL: "https://chat.lab.epam.com"
  # OPENAI_API_HOST: "https://southcentralus.api.cognitive.microsoft.com/"
  OPENAI_API_HOST: "http://openai-proxy-main.epm-gpt-common.svc.cluster.local"
  DEFAULT_MODEL: "gpt-35-turbo"
  OPENAI_API_TYPE: "azure"
  OPENAI_API_VERSION: "2023-03-15-preview"
  NEXT_PUBLIC_SHOW_MODELS: "true"
  NEXT_PUBLIC_DEFAULT_SYSTEM_PROMPT: ""
  NEXT_PUBLIC_MAX_TOKENS: "4000"
  AZURE_FUNCTIONS_API_HOST: "https://ai-proxy-function.azurewebsites.net"

podLabels:
  azure.workload.identity/use: "true"

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - '{{ include "app.fullname" . }}'
          topologyKey: kubernetes.io/hostname

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - chat.lab.epam.com
  tls:
    - secretName: wildcard-lab-epam-com
      hosts:
        - chat.lab.epam.com

serviceAccount:
  create: false
  name: epm-gpt-common

# extraEnvVarsSecret: "chat-lab-test"
