import type { DisplayAttachment } from '@epam/ai-dial-chat-shared';
import type { QuotationSource } from './quotation-source';

/** User-visible strings passed by the consuming app (via i18n or plain strings). */
export interface ConversationSourcesPanelLabels {
  /** Accessible name for the sidebar panel element. */
  ariaLabel: string;
  /** Label for the close button. */
  closeLabel: string;
  /** Placeholder text shown inside the search input. */
  searchPlaceholder: string;
  /** Accessible label for the search input clear button. */
  searchClearLabel: string;
  /** Text shown in the centred empty state when the panel has no files or sources. */
  noDataLabel: string;
  /** Text shown when a search query matches nothing. */
  noResultsLabel: string;
  /** Accessible label for the download-all icon button. */
  downloadAllLabel: string;
  /** Heading text for the uploaded-files section. */
  uploadedSectionTitle: string;
  /** Heading text for the generated-files section. */
  generatedSectionTitle: string;
  /** Heading text for the sources section. */
  sourcesSectionTitle: string;
  /** Accessible label for each source's copy-URL button. */
  copySourceLabel: string;
  /** Status message announced to assistive tech after a source URL is copied. Defaults to `'Link copied to clipboard'`. */
  sourceCopiedLabel?: string;
  /** Label passed to each attachment card's action button. */
  attachmentClickLabel: string;
}

/** CSS custom-property overrides for the sources section. */
export interface ConversationSourcesPanelColors {
  /** Source link color. */
  sourceLink?: string;
  /** Source quote text color. */
  sourceQuote?: string;
}

/** Typography (font utility class) overrides for inner elements. */
export interface ConversationSourcesPanelTypography {
  /** CSS class applied to each section heading (`<h2>`). Defaults to `'dial-body-semi-text'`. */
  sectionTitleClassName?: string;
  /** CSS class applied to each source link. Defaults to `'dial-small-text'`. */
  sourceLinkClassName?: string;
  /** CSS class applied to each source quote paragraph. Defaults to `'dial-tiny-text'`. */
  sourceQuoteClassName?: string;
}

/** Optional color and typography overrides for inner elements. */
export interface ConversationSourcesPanelStyles {
  /** Color overrides applied as CSS custom properties to the sources section. */
  colors?: ConversationSourcesPanelColors;
  /** Typography overrides for section headings and source text. */
  typography?: ConversationSourcesPanelTypography;
}

/** Props for the ConversationSourcesPanel component. */
export interface ConversationSourcesPanelProps {
  /** Whether the panel is currently visible. */
  isOpen: boolean;
  /** Called when the user requests to close the panel. */
  onClose: () => void;
  /** Attachments uploaded by the user in this conversation. */
  uploaded: DisplayAttachment[];
  /** Attachments generated by the assistant in this conversation. */
  generated: DisplayAttachment[];
  /** Quotation sources cited by the assistant. */
  sources: QuotationSource[];
  /** Called when the user activates an attachment card. */
  onAttachmentClick?: (attachment: DisplayAttachment) => void;
  /** Called when the user clicks a source link. When omitted, the link navigates normally. */
  onSourceClick?: (source: QuotationSource) => void;
  /** Called when the user activates the download-all button; omit to disable the button. */
  onDownloadAll?: () => void;
  /** Whether the viewport is in mobile breakpoint (disables resizing). */
  isMobile: boolean;
  /** Initial panel width in pixels. */
  defaultWidth?: number;
  /** Minimum panel width in pixels. */
  minWidth?: number;
  /** Maximum panel width in pixels. */
  maxWidth?: number;
  /** Called with the new width after the user finishes a resize drag. */
  onResizeStop?: (width: number) => void;
  /** User-visible strings (titles, placeholders, aria labels). */
  labels: ConversationSourcesPanelLabels;
  /** Optional typography and color class overrides for inner elements. */
  styles?: ConversationSourcesPanelStyles;
}
