name: Integration tests

on:
  pull_request:
    branches: [ development, release-* ]
  issue_comment:
    types: [created]

jobs:
  integration_tests:
    uses: epam/ai-dial-ci/.github/workflows/trigger_integration_tests.yml@1.0.2
    secrets: inherit
