name: PR Workflow

on:
  pull_request:
    branches: [development, release-*]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  run_tests:
    uses: epam/ai-dial-ci/.github/workflows/node_pr.yml@2f8f5e7c4f65c223ff255a5250cc3e36deca825b
    secrets: inherit
    with:
      node_version: 22
      severity_for_sarif_trivy: "CRITICAL,HIGH,MEDIUM"
      limit_severities_for_sarif_trivy: true