name: PR Workflow

on:
  pull_request:
    branches: [development, release-*]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  run_tests:
    uses: epam/ai-dial-ci/.github/workflows/node_pr.yml@445c37715ff0a03c13812ebb66cab39689b1487c
    secrets: inherit
    with:
      node_version: 22
      severity_trivy: "CRITICAL,HIGH,MEDIUM"
      limit_severities_for_sarif_trivy: false