name: Release Workflow

on:
  push:
    branches: [development-0.x, release-0.*]
  workflow_dispatch:
    inputs:
      promote:
        type: boolean
        default: false
        description: Promote release to stable (for release-0.* branches only)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: write
  packages: write
  security-events: write

jobs:
  release:
    uses: epam/ai-dial-ci/.github/workflows/node_release.yml@4.8.0
    with:
      promote: ${{ github.event_name == 'workflow_dispatch' && inputs.promote }}
      node-version: 24
      filter-version: '0\.[0-9]+'
      primary-branch-pattern: '^development-0\.x$'
      release-branch-pattern: '^release-0\.[0-9]+$'
      docker-development-tag: 'development-0.x'
      maximize-build-space: true
      draft-stable-releases: true
    secrets: inherit
