name: Release version

on:
  push:
    branches: [ development, release-* ]

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    uses: epam/ai-dial-ci/.github/workflows/publish_docker_gradle.yml@feat/test-ci