name: Fast image update on DEV

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag of the image to deploy"
        required: true
        type: string

env:
  NAMESPACE: dial
  DEPLOYMENT_NAME: dial-chat
  CONTAINER_NAME: application
  IMAGE_NAME: acrprhgptdev.azurecr.io/dial/ai-dial-chat

jobs:
  set-deployment-image:
    runs-on: ubuntu-latest
    environment: Dev
    permissions:
      actions: read
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: "v0.1.3"

      - name: Get K8s context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ vars.RESOURCE_GROUP }}
          cluster-name: ${{ vars.CLUSTER_NAME }}
          admin: "false"
          use-kubelogin: "true"

      - name: Update Deployment Image
        run: |
          kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} \
          ${{ env.CONTAINER_NAME }}=${{ env.IMAGE_NAME }}:${{ github.event.inputs.tag }} \
          --namespace ${{ env.NAMESPACE }}
