export * from './lib/ChatOverlay';
export * from './lib/ChatOverlayManager';

export {
  Feature,
  overlayAppName,
  OverlayEvents,
  Role,
  LikeState,
  UploadStatus,
  PublishActions,
} from '@epam/ai-dial-shared';
export type {
  ChatOverlayOptions,
  MessageButtonPlacement as MessageButtonType,
  MessageButton,
  MessageButtons,
  OverlayConversation,
  SendMessageResponse,
  SetSystemPromptResponse,
  GetMessagesResponse,
  GetConversationsResponse,
  CreateConversationResponse,
  SelectConversationResponse,
  CreatePlaybackConversationResponse,
  RenameConversationResponse,
  StopSelectedPlaybackConversationResponse,
  ExportConversationResponse,
  ImportConversationResponse,
  SelectedConversationLoadedEventResponse as SelectedConversationLoadedResponse,
  MessageCustomButtonEventResponse as MessageCustomButtonResponse,
  PrevMessagePlaybackEventResponse,
  NextMessagePlaybackEventResponse,
  EditMessageEventResponse,
  DeleteMessageEventResponse,
  UpdateMessageResponse,
  ImageMIMEType,
  MIMEType,
  Attachment,
  StageStatus,
  Stage,
  MessageSettings,
  ConversationEntityModel,
  Entity,
  EntityPublicationInfo,
  ShareInterface,
  ShareEntity,
  SharePermission,
  ConversationInfo,
  TemplateMapping,
  Message,
} from '@epam/ai-dial-shared';
